// GENERATED by tools/gen_guide.py - do not edit by hand.
//
// Every number and recipe below was read out of this pack's own item,
// recipe, loot and spawner data at build time, so the in-game guide
// cannot drift away from what the pack actually does. Change the pack,
// re-run the generator, and the guide follows.

export const GUIDE = {
  "world": {
    "radius": 50000
  },
  "sections": [
    {
      "id": "start",
      "title": "Getting In",
      "icon": "soulfire_igniter",
      "text": "Craft Soulfire and Steel from one Soul Sand and one Iron Ingot. Build a frame out of Gold Blocks exactly the way you would build a nether portal - the corners are optional - and strike the frame with the igniter. The portal burns red. Walk through.\n\nIf it will not light, the igniter tells you why: which blocks are missing, or that the opening is the wrong shape or size. Any rectangle from 2x3 up to 21x21 works.",
      "entries": []
    },
    {
      "id": "back",
      "title": "Getting Home",
      "icon": "soulfire_igniter",
      "text": "Stand in the portal you arrived through, or in the pre-lit one beside Hollow Hamlet. You come out where you left.",
      "entries": []
    },
    {
      "id": "world",
      "title": "The Five Regions",
      "icon": "soul_compass",
      "entries": [
        {
          "name": "The Misty Reach",
          "text": "Where you arrive, and where Hollow Hamlet stands. Lit, and nothing hostile spawns within 32 blocks of the shrine.\n\nLives here: Soul Wisp, Wraith."
        },
        {
          "name": "The Grave Moors",
          "text": "Headstones to the horizon. The signature look of the dimension, and the ghosts' home ground.\n\nLives here: Wraith, Banshee, Shade, Poltergeist, Fallen Knight, Soul Wisp."
        },
        {
          "name": "The Ashlands",
          "text": "Burnt red country. Demons, the deepest ore, and the only place wild dragons fly.\n\nLives here: Hellhound, Imp, Ashen Whelp, Bastion Sentinel, Veil Dragon."
        },
        {
          "name": "The Boneyard Marsh",
          "text": "Wet, luminous, and the only place with anything worth eating.\n\nLives here: Bonehide Elk, Glimmershroom Toad, Marrow Crawler, Ashwing Bat."
        },
        {
          "name": "The Sunken Ruins",
          "text": "A drowned city under guard. Bring something that shoots back.\n\nLives here: City Wraithguard, Ashwing Bat, Shade, Fallen Knight."
        }
      ],
      "text": "The Veil is a disc 50,000 blocks in every direction from the hub. Terrain builds itself around you as you travel, so there is no edge to reach quickly and nothing to load in advance."
    },
    {
      "id": "mobs",
      "title": "Creatures",
      "icon": "demon_horn",
      "entries": [
        {
          "name": "Ashen Whelp",
          "text": "A young dragon. Not tameable - it bites.\n\nHealth: 8.\n\nDrops: Embered Scale, Ember Dust, Ember Fruit."
        },
        {
          "name": "Ashwing Bat",
          "text": "Flocks. Membranes for the Featherfall Charm.\n\nHealth: 6.\n\nDrops: Ashwing Membrane."
        },
        {
          "name": "Banshee",
          "text": "Screams. Knockback plus nausea to everything nearby.\n\nHealth: 26.\n\nDrops: Soul Shard, Banshee Vocal Cord, Spectral Dust."
        },
        {
          "name": "Bastion Sentinel",
          "text": "Slow, armoured, hits like a wall falling on you.\n\nHealth: 46.\n\nDrops: Sentinel Core, Ember Coal, Ember Dust."
        },
        {
          "name": "Bonehide Elk",
          "text": "Grazes the marsh in herds. Drops hide and marrow.\n\nHealth: 18.\n\nDrops: Bonehide Elk Hide, Elk Marrow."
        },
        {
          "name": "City Wraithguard",
          "text": "Ranged. Patrols the sunken ruins in pairs.\n\nHealth: 38.\n\nDrops: Veilsteel Plating, Veilsteel Scrap, Veil Dragon Egg."
        },
        {
          "name": "Fallen Knight",
          "text": "Raises a shield periodically, refunding half the damage it takes while up.\n\nHealth: 42.\n\nDrops: Wraithsteel Scrap, Soul Shard."
        },
        {
          "name": "Glimmershroom Toad",
          "text": "Glows faintly. Drops the mucus.\n\nHealth: 8.\n\nDrops: Glimmer Mucus, Glimmershroom."
        },
        {
          "name": "Hellhound",
          "text": "Pack hunter. Sets what it bites on fire.\n\nHealth: 24.\n\nDrops: Ember Dust, Demon Horn."
        },
        {
          "name": "Imp",
          "text": "Steals an item from your bag on a lucky hit, then flees with it.\n\nHealth: 10.\n\nDrops: Ember Dust, Demon Horn."
        },
        {
          "name": "Marrow Crawler",
          "text": "Fast, low, and arrives with friends.\n\nHealth: 14.\n\nDrops: Crawler Chitin, Spectral Dust."
        },
        {
          "name": "Occultist",
          "text": "The trader at Hollow Hamlet's shrine. Right-click to shop.\n\nHealth: 30."
        },
        {
          "name": "Poltergeist",
          "text": "Cycles in and out of invisibility and throws debris. A Spirit Lantern keeps it visible.\n\nHealth: 16.\n\nDrops: Soul Shard, Spectral Dust."
        },
        {
          "name": "Shade",
          "text": "Teleports to flank you. Rarely where you last saw it.\n\nHealth: 20.\n\nDrops: Soul Shard, Spectral Dust."
        },
        {
          "name": "Soul Wisp",
          "text": "Harmless, luminous, and full of Soul Shards. It will run.\n\nHealth: 6.\n\nDrops: Soul Shard, Spectral Dust."
        },
        {
          "name": "Veil Dragon",
          "text": "Wild adults are rare in the Ashlands. Feed one Ember Fruit or Veil Marrow Stew until it accepts you, then ride it - it flies like a Happy Ghast, steered by where you look.\n\nHealth: 40.\n\nDrops: Ember Dust."
        },
        {
          "name": "Wraith",
          "text": "Blinks through thin walls instead of walking around them, and drains hunger on contact. Below 40% health it enrages: faster and larger.\n\nHealth: 22.\n\nDrops: Soul Shard, Spectral Dust."
        }
      ]
    },
    {
      "id": "gear",
      "title": "Ore Tiers & Gear",
      "icon": "hollowforged_ingot",
      "entries": [
        {
          "name": "Wraithsteel",
          "text": "Diamond-grade. Wraithsteel Ore is common below the moors; smelt the scrap.\n\nWraithsteel Axe\nAttack damage: +9.\nDurability: 900.\nCraft: 3x Wraithsteel Ingot, 2x Stick.\n\nWraithsteel Boots\nProtection: 3.\nDurability: 475.\nCraft: 4x Wraithsteel Ingot.\n\nWraithsteel Chestplate\nProtection: 8.\nDurability: 580.\nCraft: 8x Wraithsteel Ingot.\n\nWraithsteel Helm\nProtection: 3.\nDurability: 400.\nCraft: 5x Wraithsteel Ingot.\n\nWraithsteel Ingot\nSmelt: 1x Wraithsteel Scrap.\n\nWraithsteel Leggings\nProtection: 6.\nDurability: 545.\nCraft: 7x Wraithsteel Ingot.\n\nWraithsteel Pickaxe\nAttack damage: +4.\nDurability: 900.\nCraft: 3x Wraithsteel Ingot, 2x Stick.\n\nWraithsteel Scrap\n-\n\nWraithsteel Sword\nAttack damage: +7.\nDurability: 900.\nCraft: 2x Wraithsteel Ingot, 1x Stick."
        },
        {
          "name": "Veilsteel",
          "text": "Better than diamond. The ore sits deep and glows blue at the edges.\n\nVeilsteel Axe\nAttack damage: +11.\nDurability: 1500.\nCraft: 3x Veilsteel Ingot, 2x Stick.\n\nVeilsteel Boots\nProtection: 4.\nDurability: 650.\nCraft: 4x Veilsteel Ingot.\n\nVeilsteel Chestplate\nProtection: 9.\nDurability: 800.\nCraft: 8x Veilsteel Ingot.\n\nVeilsteel Helm\nProtection: 4.\nDurability: 560.\nCraft: 5x Veilsteel Ingot.\n\nVeilsteel Ingot\nSmelt: 1x Veilsteel Scrap.\n\nVeilsteel Leggings\nProtection: 7.\nDurability: 750.\nCraft: 7x Veilsteel Ingot.\n\nVeilsteel Pickaxe\nAttack damage: +5.\nDurability: 1500.\nCraft: 3x Veilsteel Ingot, 2x Stick.\n\nVeilsteel Plating\n-\n\nVeilsteel Scrap\n-\n\nVeilsteel Sword\nAttack damage: +9.\nDurability: 1500.\nCraft: 2x Veilsteel Ingot, 1x Stick."
        },
        {
          "name": "Hollowforged",
          "text": "Better than netherite, and the best gear in the pack. The ore is white with red cracks and only appears in the lowest three layers.\n\nHollowforged Axe\nAttack damage: +12.\nDurability: 1900.\nCraft: 3x Hollowforged Ingot, 2x Stick.\n\nHollowforged Boots\nProtection: 5.\nDurability: 800.\nCraft: 4x Hollowforged Ingot.\n\nHollowforged Chestplate\nProtection: 10.\nDurability: 1040.\nCraft: 8x Hollowforged Ingot.\n\nHollowforged Helm\nProtection: 5.\nDurability: 720.\nCraft: 5x Hollowforged Ingot.\n\nHollowforged Ingot\nSmelt: 1x Hollowforged Scrap.\n\nHollowforged Leggings\nProtection: 9.\nDurability: 960.\nCraft: 7x Hollowforged Ingot.\n\nHollowforged Pickaxe\nAttack damage: +6.\nDurability: 1900.\nCraft: 3x Hollowforged Ingot, 2x Stick.\n\nHollowforged Scrap\n-\n\nHollowforged Sword\nAttack damage: +10.\nDurability: 1900.\nCraft: 2x Hollowforged Ingot, 1x Stick."
        }
      ]
    },
    {
      "id": "sets",
      "title": "Armour Set Bonuses",
      "icon": "hollowforged_chestplate",
      "entries": [
        {
          "name": "Spectral Regalia",
          "text": "Below 30% health: invisibility and water breathing."
        },
        {
          "name": "Mourner's Shroud Wrap",
          "text": "Below 30% health: extra speed. Fall damage refunds half of itself as health."
        },
        {
          "name": "Ashen Demonplate",
          "text": "Permanent fire resistance and damage resistance."
        },
        {
          "name": "Hollowforged",
          "text": "Haste and fire resistance at all times, plus absorption when you drop below 30% health."
        }
      ],
      "text": "Wear all four pieces of a set to get its bonus."
    },
    {
      "id": "items",
      "title": "Items & What They Do",
      "icon": "spirit_lantern",
      "entries": [
        {
          "name": "Veil Dragon Egg",
          "text": "Right-click any block to hatch a wild Veil Dragon. Colour is random."
        },
        {
          "name": "Elk Marrow",
          "text": "Light snack, and Veil Dragons like it."
        },
        {
          "name": "Ember Coal",
          "text": "Burns for 160 seconds - twice as long as coal.\nCraft: 1x Ember Core (makes 9)."
        },
        {
          "name": "Ember Core",
          "text": "Nine Ember Coal in one block-sized lump. Uncrafts.\nCraft: 9x Ember Coal."
        },
        {
          "name": "Ember Dust",
          "text": "Ashlands currency. Trades for emeralds."
        },
        {
          "name": "Ember Fruit",
          "text": "Solid food, and the fastest way to a dragon's trust."
        },
        {
          "name": "Featherfall Charm",
          "text": "Slow falling while held. Pairs well with a dragon.\nDurability: 250.\nCraft: 3x Ashwing Membrane, 1x Spectral Dust, 1x String."
        },
        {
          "name": "Ghost Ward Charm",
          "text": "Hold it and a Wraith's touch no longer drains your hunger.\nDurability: 200.\nCraft: 1x Banshee Vocal Cord, 2x Spectral Dust, 1x Gold Ingot."
        },
        {
          "name": "Glimmershroom",
          "text": "Marsh mushroom. Goes in the stew."
        },
        {
          "name": "Hollow King's Reaper",
          "text": "Withers what it hits and heals you for a fifth of the damage dealt.\nAttack damage: +9.\nDurability: 1300."
        },
        {
          "name": "Hollow Veil Journal",
          "text": "This guide. You are handed one the first time you join; the Occultist sells replacements."
        },
        {
          "name": "Malacoda's Fang",
          "text": "Stacks burning on a target. At twelve stacks it detonates.\nAttack damage: +10.\nDurability: 1250."
        },
        {
          "name": "Sigil of the Hollow King",
          "text": "Use on a Ritual Altar to summon the Hollow King.\nCraft: 5x Soul Shard, 3x Spectral Dust, 1x Paper."
        },
        {
          "name": "Sigil of Malacoda",
          "text": "Use on a Ritual Altar to summon Malacoda.\nCraft: 3x Demon Horn, 5x Ember Dust, 1x Paper."
        },
        {
          "name": "Sigil of the Weeping Widow",
          "text": "Use on a Ritual Altar to summon the Weeping Widow.\nCraft: 2x Banshee Vocal Cord, 5x Soul Shard, 1x Paper."
        },
        {
          "name": "Soul Compass",
          "text": "Points at Hollow Hamlet and tells you how far. In a world this size that is not a luxury.\nCraft: 3x Spectral Dust, 1x Compass."
        },
        {
          "name": "Soul Shard",
          "text": "The Veil's currency. Dropped by almost everything; the Occultist takes eight for an emerald."
        },
        {
          "name": "Soulfire and Steel",
          "text": "Your way in. Works exactly like a flint and steel - and lights fires like one too - but its blue flame is what opens a gold-block frame.\nDurability: 64.\nCraft: 1x Iron Ingot, 1x Soul Sand."
        },
        {
          "name": "Spectral Dust",
          "text": "Refines into Wraithsteel at the Occultist's table."
        },
        {
          "name": "Spirit Lantern",
          "text": "Night vision while held, and it drags hidden Poltergeists back into view - they cannot stay invisible near one.\nDurability: 300.\nCraft: 2x Soul Shard, 1x Wraithsteel Ingot, 1x Glowstone Dust, 1x Soul Torch."
        },
        {
          "name": "Glimmer Mucus",
          "text": "Two make a slime ball, which nothing else here does."
        },
        {
          "name": "Veil Marrow Stew",
          "text": "The best meal in the Veil, and worth 15 dragon temper a bowl.\nCraft: 1x Elk Marrow, 1x Glimmershroom, 1x Bowl."
        },
        {
          "name": "Wailing Edge",
          "text": "Sneak and swing: everything around your target is thrown back.\nAttack damage: +8.\nDurability: 1150."
        }
      ]
    },
    {
      "id": "bosses",
      "title": "The Three Wardens",
      "icon": "sigil_hollow_king",
      "entries": [
        {
          "name": "The Hollow King",
          "text": "Sunken Crypt. Health: 200.\n\nSigil: 5x Soul Shard, 3x Spectral Dust, 1x Paper.\nUse the sigil on a Ritual Altar. The altar clears an arena around itself, walls it in and leaves a doorway, then the boss walks out.\n\nThree phases, at full health, 66% and 30%. Each phase knocks the arena back, summons adds and speeds the boss up.\n\nDrops: Hollow King's Reaper + Spectral Regalia.\n\nRe-fightable: craft another sigil once the altar has settled (20 minutes)."
        },
        {
          "name": "The Weeping Widow",
          "text": "Widow's Hollow. Health: 170.\n\nSigil: 2x Banshee Vocal Cord, 5x Soul Shard, 1x Paper.\nUse the sigil on a Ritual Altar. The altar clears an arena around itself, walls it in and leaves a doorway, then the boss walks out.\n\nThree phases, at full health, 66% and 30%. Each phase knocks the arena back, summons adds and speeds the boss up.\n\nDrops: Wailing Edge + Mourner's Shroud.\n\nRe-fightable: craft another sigil once the altar has settled (20 minutes)."
        },
        {
          "name": "Malacoda, the Ashen Demon",
          "text": "Cinder Bastion. Health: 260.\n\nSigil: 3x Demon Horn, 5x Ember Dust, 1x Paper.\nUse the sigil on a Ritual Altar. The altar clears an arena around itself, walls it in and leaves a doorway, then the boss walks out.\n\nThree phases, at full health, 66% and 30%. Each phase knocks the arena back, summons adds and speeds the boss up.\n\nDrops: Malacoda's Fang + Ashen Demonplate.\n\nRe-fightable: craft another sigil once the altar has settled (20 minutes)."
        }
      ]
    },
    {
      "id": "dragon",
      "title": "The Veil Dragon",
      "icon": "dragon_egg",
      "entries": [
        {
          "name": "Taming and flying",
          "text": "Wild adults fly over the Ashlands, rarely. There is also a Veil Dragon Egg - boss loot, or buy one from the Occultist - which hatches a wild one wherever you use it.\n\nFeed it: Ember Fruit (+8 temper), Veil Marrow Stew (+15 temper). Temper runs to 100; keep feeding until it stops throwing you.\n\nOnce tamed it can be ridden and named. It flies the way a Happy Ghast does - you steer by looking, and it climbs when you hold jump. Six colours, decided when it spawns."
        }
      ]
    },
    {
      "id": "trade",
      "title": "The Occultist",
      "icon": "soul_shard",
      "text": "Right-click the Occultist at the Hollow Hamlet shrine. The shop is a menu, not a vanilla trade screen: pick a category, pick a trade, and it checks your bag.",
      "entries": [
        {
          "name": "Currency Exchange",
          "text": "- Soul Shards x8 -> Emerald\n- Ember Dust x8 -> Emerald\n- Diamonds x3 -> 32 Soul Shards\n- Emeralds x20 -> 6 Wraithsteel Ingots\n- Emerald x3 -> Journal\n- Emerald x5 -> Soul Compass"
        },
        {
          "name": "Supplies & Trinkets",
          "text": "- Emerald x10 -> Spirit Lantern\n- Emerald x14 -> Ghost Ward Charm\n- Emerald x4 -> 8 Ashwood Logs\n- Emerald x2 -> 3 Ember Fruit\n- Spectral Dust x6 -> 2 Wraithsteel Ingots\n- Sentinel Core + Plating x2 -> 4 Veilsteel Ingots"
        },
        {
          "name": "Refined Materials",
          "text": "- Demon Horn x4 + Emerald x6 -> Enchanted Book\n- Banshee Vocal Cord x3 + Emerald x10 -> Enchanted Book\n- Diamond x6 + Embered Scale x4 -> Veil Dragon Egg"
        },
        {
          "name": "Warded Knowledge",
          "text": ""
        },
        {
          "name": "Rare Goods",
          "text": ""
        }
      ]
    }
  ]
};
