# Generated by tools/generate.js — do not hand-edit, regenerate instead.
tellraw @s {"rawtext":[{"text":"§aBuilding Auto Crop Farm (3 levels)..."}]}
fill ~0 ~0 ~0 ~12 ~0 ~12 minecraft:grass_block
fill ~1 ~1 ~1 ~11 ~5 ~11 minecraft:air
fill ~0 ~6 ~0 ~12 ~6 ~12 minecraft:cobblestone
fill ~0 ~1 ~0 ~12 ~1 ~0 minecraft:oak_fence
fill ~0 ~1 ~12 ~12 ~1 ~12 minecraft:oak_fence
fill ~0 ~1 ~0 ~0 ~1 ~12 minecraft:oak_fence
fill ~12 ~1 ~0 ~12 ~1 ~12 minecraft:oak_fence
setblock ~6 ~1 ~0 minecraft:sea_lantern
setblock ~6 ~1 ~12 minecraft:sea_lantern
setblock ~0 ~1 ~6 minecraft:sea_lantern
setblock ~12 ~1 ~6 minecraft:sea_lantern
setblock ~5 ~0 ~1 minecraft:farmland
setblock ~5 ~1 ~1 minecraft:wheat["growth"=7]
setblock ~6 ~0 ~1 minecraft:farmland
setblock ~6 ~1 ~1 minecraft:wheat["growth"=0]
setblock ~7 ~0 ~1 minecraft:farmland
setblock ~7 ~1 ~1 minecraft:wheat["growth"=3]
setblock ~5 ~0 ~2 minecraft:farmland
setblock ~5 ~1 ~2 minecraft:wheat["growth"=5]
setblock ~7 ~0 ~2 minecraft:farmland
setblock ~7 ~1 ~2 minecraft:wheat["growth"=3]
setblock ~5 ~0 ~3 minecraft:farmland
setblock ~5 ~1 ~3 minecraft:wheat["growth"=2]
setblock ~6 ~0 ~3 minecraft:farmland
setblock ~6 ~1 ~3 minecraft:wheat["growth"=4]
setblock ~7 ~0 ~3 minecraft:farmland
setblock ~7 ~1 ~3 minecraft:wheat["growth"=4]
setblock ~6 ~0 ~2 minecraft:water
setblock ~5 ~0 ~1 minecraft:grass_block
setblock ~5 ~1 ~1 minecraft:composter
fill ~4 ~1 ~0 ~4 ~1 ~4 minecraft:oak_fence
fill ~8 ~1 ~0 ~8 ~1 ~4 minecraft:oak_fence
setblock ~5 ~1 ~4 minecraft:oak_fence
setblock ~7 ~1 ~4 minecraft:oak_fence
setblock ~6 ~1 ~4 minecraft:air
summon minecraft:villager ~7 ~1 ~2
setblock ~5 ~0 ~9 minecraft:farmland
setblock ~5 ~1 ~9 minecraft:wheat["growth"=2]
setblock ~6 ~0 ~9 minecraft:farmland
setblock ~6 ~1 ~9 minecraft:wheat["growth"=1]
setblock ~7 ~0 ~9 minecraft:farmland
setblock ~7 ~1 ~9 minecraft:wheat["growth"=1]
setblock ~5 ~0 ~10 minecraft:farmland
setblock ~5 ~1 ~10 minecraft:wheat["growth"=3]
setblock ~7 ~0 ~10 minecraft:farmland
setblock ~7 ~1 ~10 minecraft:wheat["growth"=5]
setblock ~5 ~0 ~11 minecraft:farmland
setblock ~5 ~1 ~11 minecraft:wheat["growth"=3]
setblock ~6 ~0 ~11 minecraft:farmland
setblock ~6 ~1 ~11 minecraft:wheat["growth"=4]
setblock ~7 ~0 ~11 minecraft:farmland
setblock ~7 ~1 ~11 minecraft:wheat["growth"=5]
setblock ~6 ~0 ~10 minecraft:water
setblock ~5 ~0 ~11 minecraft:grass_block
setblock ~5 ~1 ~11 minecraft:composter
fill ~4 ~1 ~8 ~4 ~1 ~12 minecraft:oak_fence
fill ~8 ~1 ~8 ~8 ~1 ~12 minecraft:oak_fence
setblock ~5 ~1 ~8 minecraft:oak_fence
setblock ~7 ~1 ~8 minecraft:oak_fence
setblock ~6 ~1 ~8 minecraft:air
summon minecraft:villager ~7 ~1 ~10
setblock ~1 ~0 ~5 minecraft:farmland
setblock ~1 ~1 ~5 minecraft:wheat["growth"=4]
setblock ~1 ~0 ~6 minecraft:farmland
setblock ~1 ~1 ~6 minecraft:wheat["growth"=6]
setblock ~1 ~0 ~7 minecraft:farmland
setblock ~1 ~1 ~7 minecraft:wheat["growth"=2]
setblock ~2 ~0 ~5 minecraft:farmland
setblock ~2 ~1 ~5 minecraft:wheat["growth"=7]
setblock ~2 ~0 ~7 minecraft:farmland
setblock ~2 ~1 ~7 minecraft:wheat["growth"=3]
setblock ~3 ~0 ~5 minecraft:farmland
setblock ~3 ~1 ~5 minecraft:wheat["growth"=1]
setblock ~3 ~0 ~6 minecraft:farmland
setblock ~3 ~1 ~6 minecraft:wheat["growth"=7]
setblock ~3 ~0 ~7 minecraft:farmland
setblock ~3 ~1 ~7 minecraft:wheat["growth"=3]
setblock ~2 ~0 ~6 minecraft:water
setblock ~1 ~0 ~5 minecraft:grass_block
setblock ~1 ~1 ~5 minecraft:composter
fill ~0 ~1 ~4 ~4 ~1 ~4 minecraft:oak_fence
fill ~0 ~1 ~8 ~4 ~1 ~8 minecraft:oak_fence
setblock ~4 ~1 ~5 minecraft:oak_fence
setblock ~4 ~1 ~7 minecraft:oak_fence
setblock ~4 ~1 ~6 minecraft:air
summon minecraft:villager ~2 ~1 ~7
setblock ~9 ~0 ~5 minecraft:farmland
setblock ~9 ~1 ~5 minecraft:wheat["growth"=4]
setblock ~9 ~0 ~6 minecraft:farmland
setblock ~9 ~1 ~6 minecraft:wheat["growth"=7]
setblock ~9 ~0 ~7 minecraft:farmland
setblock ~9 ~1 ~7 minecraft:wheat["growth"=1]
setblock ~10 ~0 ~5 minecraft:farmland
setblock ~10 ~1 ~5 minecraft:wheat["growth"=2]
setblock ~10 ~0 ~7 minecraft:farmland
setblock ~10 ~1 ~7 minecraft:wheat["growth"=0]
setblock ~11 ~0 ~5 minecraft:farmland
setblock ~11 ~1 ~5 minecraft:wheat["growth"=6]
setblock ~11 ~0 ~6 minecraft:farmland
setblock ~11 ~1 ~6 minecraft:wheat["growth"=6]
setblock ~11 ~0 ~7 minecraft:farmland
setblock ~11 ~1 ~7 minecraft:wheat["growth"=2]
setblock ~10 ~0 ~6 minecraft:water
setblock ~11 ~0 ~5 minecraft:grass_block
setblock ~11 ~1 ~5 minecraft:composter
fill ~8 ~1 ~4 ~12 ~1 ~4 minecraft:oak_fence
fill ~8 ~1 ~8 ~12 ~1 ~8 minecraft:oak_fence
setblock ~8 ~1 ~5 minecraft:oak_fence
setblock ~8 ~1 ~7 minecraft:oak_fence
setblock ~8 ~1 ~6 minecraft:air
summon minecraft:villager ~10 ~1 ~7
fill ~4 ~1 ~4 ~4 ~1 ~8 minecraft:oak_fence
fill ~8 ~1 ~4 ~8 ~1 ~8 minecraft:oak_fence
fill ~4 ~1 ~4 ~8 ~1 ~4 minecraft:oak_fence
fill ~4 ~1 ~8 ~8 ~1 ~8 minecraft:oak_fence
setblock ~4 ~1 ~6 minecraft:air
setblock ~8 ~1 ~6 minecraft:air
setblock ~6 ~1 ~4 minecraft:air
setblock ~6 ~1 ~8 minecraft:air
summon minecraft:villager ~6 ~1 ~6
setblock ~6 ~0 ~5 minecraft:hopper["facing_direction"=3]
setblock ~6 ~1 ~5 minecraft:rail
summon minecraft:hopper_minecart ~6 ~1 ~5
setblock ~6 ~0 ~7 minecraft:hopper["facing_direction"=2]
setblock ~6 ~1 ~7 minecraft:rail
summon minecraft:hopper_minecart ~6 ~1 ~7
setblock ~5 ~0 ~6 minecraft:hopper["facing_direction"=5]
setblock ~5 ~1 ~6 minecraft:rail
summon minecraft:hopper_minecart ~5 ~1 ~6
setblock ~7 ~0 ~6 minecraft:hopper["facing_direction"=4]
setblock ~7 ~1 ~6 minecraft:rail
summon minecraft:hopper_minecart ~7 ~1 ~6
setblock ~6 ~0 ~6 minecraft:hopper["facing_direction"=0]
setblock ~6 ~1 ~6 minecraft:rail
summon minecraft:hopper_minecart ~6 ~1 ~6
setblock ~6 ~-1 ~6 minecraft:hopper["facing_direction"=4]
setblock ~5 ~-1 ~6 minecraft:hopper["facing_direction"=4]
setblock ~4 ~-1 ~6 minecraft:hopper["facing_direction"=4]
setblock ~3 ~-1 ~6 minecraft:hopper["facing_direction"=4]
setblock ~2 ~-1 ~6 minecraft:hopper["facing_direction"=4]
setblock ~1 ~-1 ~6 minecraft:hopper["facing_direction"=4]
setblock ~0 ~-1 ~6 minecraft:hopper["facing_direction"=4]
setblock ~-1 ~-1 ~6 minecraft:hopper["facing_direction"=0]
fill ~0 ~9 ~0 ~12 ~9 ~12 minecraft:grass_block
fill ~1 ~10 ~1 ~11 ~14 ~11 minecraft:air
fill ~0 ~15 ~0 ~12 ~15 ~12 minecraft:cobblestone
fill ~0 ~10 ~0 ~12 ~10 ~0 minecraft:oak_fence
fill ~0 ~10 ~12 ~12 ~10 ~12 minecraft:oak_fence
fill ~0 ~10 ~0 ~0 ~10 ~12 minecraft:oak_fence
fill ~12 ~10 ~0 ~12 ~10 ~12 minecraft:oak_fence
setblock ~6 ~10 ~0 minecraft:sea_lantern
setblock ~6 ~10 ~12 minecraft:sea_lantern
setblock ~0 ~10 ~6 minecraft:sea_lantern
setblock ~12 ~10 ~6 minecraft:sea_lantern
setblock ~5 ~9 ~1 minecraft:farmland
setblock ~5 ~10 ~1 minecraft:wheat["growth"=4]
setblock ~6 ~9 ~1 minecraft:farmland
setblock ~6 ~10 ~1 minecraft:wheat["growth"=3]
setblock ~7 ~9 ~1 minecraft:farmland
setblock ~7 ~10 ~1 minecraft:wheat["growth"=0]
setblock ~5 ~9 ~2 minecraft:farmland
setblock ~5 ~10 ~2 minecraft:wheat["growth"=1]
setblock ~7 ~9 ~2 minecraft:farmland
setblock ~7 ~10 ~2 minecraft:wheat["growth"=5]
setblock ~5 ~9 ~3 minecraft:farmland
setblock ~5 ~10 ~3 minecraft:wheat["growth"=0]
setblock ~6 ~9 ~3 minecraft:farmland
setblock ~6 ~10 ~3 minecraft:wheat["growth"=6]
setblock ~7 ~9 ~3 minecraft:farmland
setblock ~7 ~10 ~3 minecraft:wheat["growth"=4]
setblock ~6 ~9 ~2 minecraft:water
setblock ~5 ~9 ~1 minecraft:grass_block
setblock ~5 ~10 ~1 minecraft:composter
fill ~4 ~10 ~0 ~4 ~10 ~4 minecraft:oak_fence
fill ~8 ~10 ~0 ~8 ~10 ~4 minecraft:oak_fence
setblock ~5 ~10 ~4 minecraft:oak_fence
setblock ~7 ~10 ~4 minecraft:oak_fence
setblock ~6 ~10 ~4 minecraft:air
summon minecraft:villager ~7 ~10 ~2
setblock ~5 ~9 ~9 minecraft:farmland
setblock ~5 ~10 ~9 minecraft:wheat["growth"=6]
setblock ~6 ~9 ~9 minecraft:farmland
setblock ~6 ~10 ~9 minecraft:wheat["growth"=5]
setblock ~7 ~9 ~9 minecraft:farmland
setblock ~7 ~10 ~9 minecraft:wheat["growth"=1]
setblock ~5 ~9 ~10 minecraft:farmland
setblock ~5 ~10 ~10 minecraft:wheat["growth"=5]
setblock ~7 ~9 ~10 minecraft:farmland
setblock ~7 ~10 ~10 minecraft:wheat["growth"=6]
setblock ~5 ~9 ~11 minecraft:farmland
setblock ~5 ~10 ~11 minecraft:wheat["growth"=2]
setblock ~6 ~9 ~11 minecraft:farmland
setblock ~6 ~10 ~11 minecraft:wheat["growth"=5]
setblock ~7 ~9 ~11 minecraft:farmland
setblock ~7 ~10 ~11 minecraft:wheat["growth"=0]
setblock ~6 ~9 ~10 minecraft:water
setblock ~5 ~9 ~11 minecraft:grass_block
setblock ~5 ~10 ~11 minecraft:composter
fill ~4 ~10 ~8 ~4 ~10 ~12 minecraft:oak_fence
fill ~8 ~10 ~8 ~8 ~10 ~12 minecraft:oak_fence
setblock ~5 ~10 ~8 minecraft:oak_fence
setblock ~7 ~10 ~8 minecraft:oak_fence
setblock ~6 ~10 ~8 minecraft:air
summon minecraft:villager ~7 ~10 ~10
setblock ~1 ~9 ~5 minecraft:farmland
setblock ~1 ~10 ~5 minecraft:wheat["growth"=7]
setblock ~1 ~9 ~6 minecraft:farmland
setblock ~1 ~10 ~6 minecraft:wheat["growth"=5]
setblock ~1 ~9 ~7 minecraft:farmland
setblock ~1 ~10 ~7 minecraft:wheat["growth"=4]
setblock ~2 ~9 ~5 minecraft:farmland
setblock ~2 ~10 ~5 minecraft:wheat["growth"=4]
setblock ~2 ~9 ~7 minecraft:farmland
setblock ~2 ~10 ~7 minecraft:wheat["growth"=2]
setblock ~3 ~9 ~5 minecraft:farmland
setblock ~3 ~10 ~5 minecraft:wheat["growth"=2]
setblock ~3 ~9 ~6 minecraft:farmland
setblock ~3 ~10 ~6 minecraft:wheat["growth"=5]
setblock ~3 ~9 ~7 minecraft:farmland
setblock ~3 ~10 ~7 minecraft:wheat["growth"=6]
setblock ~2 ~9 ~6 minecraft:water
setblock ~1 ~9 ~5 minecraft:grass_block
setblock ~1 ~10 ~5 minecraft:composter
fill ~0 ~10 ~4 ~4 ~10 ~4 minecraft:oak_fence
fill ~0 ~10 ~8 ~4 ~10 ~8 minecraft:oak_fence
setblock ~4 ~10 ~5 minecraft:oak_fence
setblock ~4 ~10 ~7 minecraft:oak_fence
setblock ~4 ~10 ~6 minecraft:air
summon minecraft:villager ~2 ~10 ~7
setblock ~9 ~9 ~5 minecraft:farmland
setblock ~9 ~10 ~5 minecraft:wheat["growth"=3]
setblock ~9 ~9 ~6 minecraft:farmland
setblock ~9 ~10 ~6 minecraft:wheat["growth"=4]
setblock ~9 ~9 ~7 minecraft:farmland
setblock ~9 ~10 ~7 minecraft:wheat["growth"=0]
setblock ~10 ~9 ~5 minecraft:farmland
setblock ~10 ~10 ~5 minecraft:wheat["growth"=5]
setblock ~10 ~9 ~7 minecraft:farmland
setblock ~10 ~10 ~7 minecraft:wheat["growth"=2]
setblock ~11 ~9 ~5 minecraft:farmland
setblock ~11 ~10 ~5 minecraft:wheat["growth"=3]
setblock ~11 ~9 ~6 minecraft:farmland
setblock ~11 ~10 ~6 minecraft:wheat["growth"=1]
setblock ~11 ~9 ~7 minecraft:farmland
setblock ~11 ~10 ~7 minecraft:wheat["growth"=2]
setblock ~10 ~9 ~6 minecraft:water
setblock ~11 ~9 ~5 minecraft:grass_block
setblock ~11 ~10 ~5 minecraft:composter
fill ~8 ~10 ~4 ~12 ~10 ~4 minecraft:oak_fence
fill ~8 ~10 ~8 ~12 ~10 ~8 minecraft:oak_fence
setblock ~8 ~10 ~5 minecraft:oak_fence
setblock ~8 ~10 ~7 minecraft:oak_fence
setblock ~8 ~10 ~6 minecraft:air
summon minecraft:villager ~10 ~10 ~7
fill ~4 ~10 ~4 ~4 ~10 ~8 minecraft:oak_fence
fill ~8 ~10 ~4 ~8 ~10 ~8 minecraft:oak_fence
fill ~4 ~10 ~4 ~8 ~10 ~4 minecraft:oak_fence
fill ~4 ~10 ~8 ~8 ~10 ~8 minecraft:oak_fence
setblock ~4 ~10 ~6 minecraft:air
setblock ~8 ~10 ~6 minecraft:air
setblock ~6 ~10 ~4 minecraft:air
setblock ~6 ~10 ~8 minecraft:air
summon minecraft:villager ~6 ~10 ~6
setblock ~6 ~9 ~5 minecraft:hopper["facing_direction"=3]
setblock ~6 ~10 ~5 minecraft:rail
summon minecraft:hopper_minecart ~6 ~10 ~5
setblock ~6 ~9 ~7 minecraft:hopper["facing_direction"=2]
setblock ~6 ~10 ~7 minecraft:rail
summon minecraft:hopper_minecart ~6 ~10 ~7
setblock ~5 ~9 ~6 minecraft:hopper["facing_direction"=5]
setblock ~5 ~10 ~6 minecraft:rail
summon minecraft:hopper_minecart ~5 ~10 ~6
setblock ~7 ~9 ~6 minecraft:hopper["facing_direction"=4]
setblock ~7 ~10 ~6 minecraft:rail
summon minecraft:hopper_minecart ~7 ~10 ~6
setblock ~6 ~9 ~6 minecraft:hopper["facing_direction"=0]
setblock ~6 ~10 ~6 minecraft:rail
summon minecraft:hopper_minecart ~6 ~10 ~6
setblock ~6 ~8 ~6 minecraft:hopper["facing_direction"=4]
setblock ~5 ~8 ~6 minecraft:hopper["facing_direction"=4]
setblock ~4 ~8 ~6 minecraft:hopper["facing_direction"=4]
setblock ~3 ~8 ~6 minecraft:hopper["facing_direction"=4]
setblock ~2 ~8 ~6 minecraft:hopper["facing_direction"=4]
setblock ~1 ~8 ~6 minecraft:hopper["facing_direction"=4]
setblock ~0 ~8 ~6 minecraft:hopper["facing_direction"=4]
setblock ~-1 ~8 ~6 minecraft:hopper["facing_direction"=0]
fill ~0 ~18 ~0 ~12 ~18 ~12 minecraft:grass_block
fill ~1 ~19 ~1 ~11 ~23 ~11 minecraft:air
fill ~0 ~24 ~0 ~12 ~24 ~12 minecraft:cobblestone
fill ~0 ~19 ~0 ~12 ~19 ~0 minecraft:oak_fence
fill ~0 ~19 ~12 ~12 ~19 ~12 minecraft:oak_fence
fill ~0 ~19 ~0 ~0 ~19 ~12 minecraft:oak_fence
fill ~12 ~19 ~0 ~12 ~19 ~12 minecraft:oak_fence
setblock ~6 ~19 ~0 minecraft:sea_lantern
setblock ~6 ~19 ~12 minecraft:sea_lantern
setblock ~0 ~19 ~6 minecraft:sea_lantern
setblock ~12 ~19 ~6 minecraft:sea_lantern
setblock ~5 ~18 ~1 minecraft:farmland
setblock ~5 ~19 ~1 minecraft:wheat["growth"=2]
setblock ~6 ~18 ~1 minecraft:farmland
setblock ~6 ~19 ~1 minecraft:wheat["growth"=6]
setblock ~7 ~18 ~1 minecraft:farmland
setblock ~7 ~19 ~1 minecraft:wheat["growth"=2]
setblock ~5 ~18 ~2 minecraft:farmland
setblock ~5 ~19 ~2 minecraft:wheat["growth"=1]
setblock ~7 ~18 ~2 minecraft:farmland
setblock ~7 ~19 ~2 minecraft:wheat["growth"=4]
setblock ~5 ~18 ~3 minecraft:farmland
setblock ~5 ~19 ~3 minecraft:wheat["growth"=5]
setblock ~6 ~18 ~3 minecraft:farmland
setblock ~6 ~19 ~3 minecraft:wheat["growth"=1]
setblock ~7 ~18 ~3 minecraft:farmland
setblock ~7 ~19 ~3 minecraft:wheat["growth"=1]
setblock ~6 ~18 ~2 minecraft:water
setblock ~5 ~18 ~1 minecraft:grass_block
setblock ~5 ~19 ~1 minecraft:composter
fill ~4 ~19 ~0 ~4 ~19 ~4 minecraft:oak_fence
fill ~8 ~19 ~0 ~8 ~19 ~4 minecraft:oak_fence
setblock ~5 ~19 ~4 minecraft:oak_fence
setblock ~7 ~19 ~4 minecraft:oak_fence
setblock ~6 ~19 ~4 minecraft:air
summon minecraft:villager ~7 ~19 ~2
setblock ~5 ~18 ~9 minecraft:farmland
setblock ~5 ~19 ~9 minecraft:wheat["growth"=2]
setblock ~6 ~18 ~9 minecraft:farmland
setblock ~6 ~19 ~9 minecraft:wheat["growth"=7]
setblock ~7 ~18 ~9 minecraft:farmland
setblock ~7 ~19 ~9 minecraft:wheat["growth"=0]
setblock ~5 ~18 ~10 minecraft:farmland
setblock ~5 ~19 ~10 minecraft:wheat["growth"=3]
setblock ~7 ~18 ~10 minecraft:farmland
setblock ~7 ~19 ~10 minecraft:wheat["growth"=5]
setblock ~5 ~18 ~11 minecraft:farmland
setblock ~5 ~19 ~11 minecraft:wheat["growth"=6]
setblock ~6 ~18 ~11 minecraft:farmland
setblock ~6 ~19 ~11 minecraft:wheat["growth"=4]
setblock ~7 ~18 ~11 minecraft:farmland
setblock ~7 ~19 ~11 minecraft:wheat["growth"=5]
setblock ~6 ~18 ~10 minecraft:water
setblock ~5 ~18 ~11 minecraft:grass_block
setblock ~5 ~19 ~11 minecraft:composter
fill ~4 ~19 ~8 ~4 ~19 ~12 minecraft:oak_fence
fill ~8 ~19 ~8 ~8 ~19 ~12 minecraft:oak_fence
setblock ~5 ~19 ~8 minecraft:oak_fence
setblock ~7 ~19 ~8 minecraft:oak_fence
setblock ~6 ~19 ~8 minecraft:air
summon minecraft:villager ~7 ~19 ~10
setblock ~1 ~18 ~5 minecraft:farmland
setblock ~1 ~19 ~5 minecraft:wheat["growth"=2]
setblock ~1 ~18 ~6 minecraft:farmland
setblock ~1 ~19 ~6 minecraft:wheat["growth"=1]
setblock ~1 ~18 ~7 minecraft:farmland
setblock ~1 ~19 ~7 minecraft:wheat["growth"=5]
setblock ~2 ~18 ~5 minecraft:farmland
setblock ~2 ~19 ~5 minecraft:wheat["growth"=3]
setblock ~2 ~18 ~7 minecraft:farmland
setblock ~2 ~19 ~7 minecraft:wheat["growth"=7]
setblock ~3 ~18 ~5 minecraft:farmland
setblock ~3 ~19 ~5 minecraft:wheat["growth"=4]
setblock ~3 ~18 ~6 minecraft:farmland
setblock ~3 ~19 ~6 minecraft:wheat["growth"=0]
setblock ~3 ~18 ~7 minecraft:farmland
setblock ~3 ~19 ~7 minecraft:wheat["growth"=0]
setblock ~2 ~18 ~6 minecraft:water
setblock ~1 ~18 ~5 minecraft:grass_block
setblock ~1 ~19 ~5 minecraft:composter
fill ~0 ~19 ~4 ~4 ~19 ~4 minecraft:oak_fence
fill ~0 ~19 ~8 ~4 ~19 ~8 minecraft:oak_fence
setblock ~4 ~19 ~5 minecraft:oak_fence
setblock ~4 ~19 ~7 minecraft:oak_fence
setblock ~4 ~19 ~6 minecraft:air
summon minecraft:villager ~2 ~19 ~7
setblock ~9 ~18 ~5 minecraft:farmland
setblock ~9 ~19 ~5 minecraft:wheat["growth"=2]
setblock ~9 ~18 ~6 minecraft:farmland
setblock ~9 ~19 ~6 minecraft:wheat["growth"=7]
setblock ~9 ~18 ~7 minecraft:farmland
setblock ~9 ~19 ~7 minecraft:wheat["growth"=1]
setblock ~10 ~18 ~5 minecraft:farmland
setblock ~10 ~19 ~5 minecraft:wheat["growth"=4]
setblock ~10 ~18 ~7 minecraft:farmland
setblock ~10 ~19 ~7 minecraft:wheat["growth"=0]
setblock ~11 ~18 ~5 minecraft:farmland
setblock ~11 ~19 ~5 minecraft:wheat["growth"=4]
setblock ~11 ~18 ~6 minecraft:farmland
setblock ~11 ~19 ~6 minecraft:wheat["growth"=2]
setblock ~11 ~18 ~7 minecraft:farmland
setblock ~11 ~19 ~7 minecraft:wheat["growth"=1]
setblock ~10 ~18 ~6 minecraft:water
setblock ~11 ~18 ~5 minecraft:grass_block
setblock ~11 ~19 ~5 minecraft:composter
fill ~8 ~19 ~4 ~12 ~19 ~4 minecraft:oak_fence
fill ~8 ~19 ~8 ~12 ~19 ~8 minecraft:oak_fence
setblock ~8 ~19 ~5 minecraft:oak_fence
setblock ~8 ~19 ~7 minecraft:oak_fence
setblock ~8 ~19 ~6 minecraft:air
summon minecraft:villager ~10 ~19 ~7
fill ~4 ~19 ~4 ~4 ~19 ~8 minecraft:oak_fence
fill ~8 ~19 ~4 ~8 ~19 ~8 minecraft:oak_fence
fill ~4 ~19 ~4 ~8 ~19 ~4 minecraft:oak_fence
fill ~4 ~19 ~8 ~8 ~19 ~8 minecraft:oak_fence
setblock ~4 ~19 ~6 minecraft:air
setblock ~8 ~19 ~6 minecraft:air
setblock ~6 ~19 ~4 minecraft:air
setblock ~6 ~19 ~8 minecraft:air
summon minecraft:villager ~6 ~19 ~6
setblock ~6 ~18 ~5 minecraft:hopper["facing_direction"=3]
setblock ~6 ~19 ~5 minecraft:rail
summon minecraft:hopper_minecart ~6 ~19 ~5
setblock ~6 ~18 ~7 minecraft:hopper["facing_direction"=2]
setblock ~6 ~19 ~7 minecraft:rail
summon minecraft:hopper_minecart ~6 ~19 ~7
setblock ~5 ~18 ~6 minecraft:hopper["facing_direction"=5]
setblock ~5 ~19 ~6 minecraft:rail
summon minecraft:hopper_minecart ~5 ~19 ~6
setblock ~7 ~18 ~6 minecraft:hopper["facing_direction"=4]
setblock ~7 ~19 ~6 minecraft:rail
summon minecraft:hopper_minecart ~7 ~19 ~6
setblock ~6 ~18 ~6 minecraft:hopper["facing_direction"=0]
setblock ~6 ~19 ~6 minecraft:rail
summon minecraft:hopper_minecart ~6 ~19 ~6
setblock ~6 ~17 ~6 minecraft:hopper["facing_direction"=4]
setblock ~5 ~17 ~6 minecraft:hopper["facing_direction"=4]
setblock ~4 ~17 ~6 minecraft:hopper["facing_direction"=4]
setblock ~3 ~17 ~6 minecraft:hopper["facing_direction"=4]
setblock ~2 ~17 ~6 minecraft:hopper["facing_direction"=4]
setblock ~1 ~17 ~6 minecraft:hopper["facing_direction"=4]
setblock ~0 ~17 ~6 minecraft:hopper["facing_direction"=4]
setblock ~-1 ~17 ~6 minecraft:hopper["facing_direction"=0]
setblock ~-1 ~-3 ~6 minecraft:chest
setblock ~-2 ~-3 ~6 minecraft:chest
setblock ~-1 ~-2 ~6 minecraft:hopper["facing_direction"=0]
setblock ~-1 ~-1 ~6 minecraft:hopper["facing_direction"=0]
setblock ~-1 ~0 ~6 minecraft:hopper["facing_direction"=0]
setblock ~-1 ~1 ~6 minecraft:hopper["facing_direction"=0]
setblock ~-1 ~2 ~6 minecraft:hopper["facing_direction"=0]
setblock ~-1 ~3 ~6 minecraft:hopper["facing_direction"=0]
setblock ~-1 ~4 ~6 minecraft:hopper["facing_direction"=0]
setblock ~-1 ~5 ~6 minecraft:hopper["facing_direction"=0]
setblock ~-1 ~6 ~6 minecraft:hopper["facing_direction"=0]
setblock ~-1 ~7 ~6 minecraft:hopper["facing_direction"=0]
setblock ~-1 ~8 ~6 minecraft:hopper["facing_direction"=0]
setblock ~-1 ~9 ~6 minecraft:hopper["facing_direction"=0]
setblock ~-1 ~10 ~6 minecraft:hopper["facing_direction"=0]
setblock ~-1 ~11 ~6 minecraft:hopper["facing_direction"=0]
setblock ~-1 ~12 ~6 minecraft:hopper["facing_direction"=0]
setblock ~-1 ~13 ~6 minecraft:hopper["facing_direction"=0]
setblock ~-1 ~14 ~6 minecraft:hopper["facing_direction"=0]
setblock ~-1 ~15 ~6 minecraft:hopper["facing_direction"=0]
setblock ~-1 ~16 ~6 minecraft:hopper["facing_direction"=0]
setblock ~-1 ~17 ~6 minecraft:hopper["facing_direction"=0]
tellraw @s {"rawtext":[{"text":"§aDone."}]}
