# Generated by tools/generate.js — do not hand-edit, regenerate instead.
tellraw @s {"rawtext":[{"text":"§aBuilding Auto Crop Farm (1 level)..."}]}
fill ~0 ~0 ~0 ~12 ~0 ~12 minecraft:grass_block
fill ~1 ~1 ~1 ~11 ~5 ~11 minecraft:air
fill ~0 ~6 ~0 ~12 ~6 ~12 minecraft:cobblestone
fill ~0 ~1 ~0 ~12 ~1 ~0 minecraft:oak_fence
fill ~0 ~1 ~12 ~12 ~1 ~12 minecraft:oak_fence
fill ~0 ~1 ~0 ~0 ~1 ~12 minecraft:oak_fence
fill ~12 ~1 ~0 ~12 ~1 ~12 minecraft:oak_fence
setblock ~6 ~1 ~0 minecraft:sea_lantern
setblock ~6 ~1 ~12 minecraft:sea_lantern
setblock ~0 ~1 ~6 minecraft:sea_lantern
setblock ~12 ~1 ~6 minecraft:sea_lantern
setblock ~5 ~0 ~1 minecraft:farmland
setblock ~5 ~1 ~1 minecraft:wheat["growth"=2]
setblock ~6 ~0 ~1 minecraft:farmland
setblock ~6 ~1 ~1 minecraft:wheat["growth"=4]
setblock ~7 ~0 ~1 minecraft:farmland
setblock ~7 ~1 ~1 minecraft:wheat["growth"=3]
setblock ~5 ~0 ~2 minecraft:farmland
setblock ~5 ~1 ~2 minecraft:wheat["growth"=5]
setblock ~7 ~0 ~2 minecraft:farmland
setblock ~7 ~1 ~2 minecraft:wheat["growth"=4]
setblock ~5 ~0 ~3 minecraft:farmland
setblock ~5 ~1 ~3 minecraft:wheat["growth"=7]
setblock ~6 ~0 ~3 minecraft:farmland
setblock ~6 ~1 ~3 minecraft:wheat["growth"=4]
setblock ~7 ~0 ~3 minecraft:farmland
setblock ~7 ~1 ~3 minecraft:wheat["growth"=2]
setblock ~6 ~0 ~2 minecraft:water
setblock ~5 ~0 ~1 minecraft:grass_block
setblock ~5 ~1 ~1 minecraft:composter
fill ~4 ~1 ~0 ~4 ~1 ~4 minecraft:oak_fence
fill ~8 ~1 ~0 ~8 ~1 ~4 minecraft:oak_fence
setblock ~5 ~1 ~4 minecraft:oak_fence
setblock ~7 ~1 ~4 minecraft:oak_fence
setblock ~6 ~1 ~4 minecraft:air
summon minecraft:villager ~7 ~1 ~2
setblock ~5 ~0 ~9 minecraft:farmland
setblock ~5 ~1 ~9 minecraft:wheat["growth"=1]
setblock ~6 ~0 ~9 minecraft:farmland
setblock ~6 ~1 ~9 minecraft:wheat["growth"=5]
setblock ~7 ~0 ~9 minecraft:farmland
setblock ~7 ~1 ~9 minecraft:wheat["growth"=1]
setblock ~5 ~0 ~10 minecraft:farmland
setblock ~5 ~1 ~10 minecraft:wheat["growth"=6]
setblock ~7 ~0 ~10 minecraft:farmland
setblock ~7 ~1 ~10 minecraft:wheat["growth"=4]
setblock ~5 ~0 ~11 minecraft:farmland
setblock ~5 ~1 ~11 minecraft:wheat["growth"=5]
setblock ~6 ~0 ~11 minecraft:farmland
setblock ~6 ~1 ~11 minecraft:wheat["growth"=5]
setblock ~7 ~0 ~11 minecraft:farmland
setblock ~7 ~1 ~11 minecraft:wheat["growth"=3]
setblock ~6 ~0 ~10 minecraft:water
setblock ~5 ~0 ~11 minecraft:grass_block
setblock ~5 ~1 ~11 minecraft:composter
fill ~4 ~1 ~8 ~4 ~1 ~12 minecraft:oak_fence
fill ~8 ~1 ~8 ~8 ~1 ~12 minecraft:oak_fence
setblock ~5 ~1 ~8 minecraft:oak_fence
setblock ~7 ~1 ~8 minecraft:oak_fence
setblock ~6 ~1 ~8 minecraft:air
summon minecraft:villager ~7 ~1 ~10
setblock ~1 ~0 ~5 minecraft:farmland
setblock ~1 ~1 ~5 minecraft:wheat["growth"=5]
setblock ~1 ~0 ~6 minecraft:farmland
setblock ~1 ~1 ~6 minecraft:wheat["growth"=0]
setblock ~1 ~0 ~7 minecraft:farmland
setblock ~1 ~1 ~7 minecraft:wheat["growth"=0]
setblock ~2 ~0 ~5 minecraft:farmland
setblock ~2 ~1 ~5 minecraft:wheat["growth"=6]
setblock ~2 ~0 ~7 minecraft:farmland
setblock ~2 ~1 ~7 minecraft:wheat["growth"=7]
setblock ~3 ~0 ~5 minecraft:farmland
setblock ~3 ~1 ~5 minecraft:wheat["growth"=2]
setblock ~3 ~0 ~6 minecraft:farmland
setblock ~3 ~1 ~6 minecraft:wheat["growth"=5]
setblock ~3 ~0 ~7 minecraft:farmland
setblock ~3 ~1 ~7 minecraft:wheat["growth"=0]
setblock ~2 ~0 ~6 minecraft:water
setblock ~1 ~0 ~5 minecraft:grass_block
setblock ~1 ~1 ~5 minecraft:composter
fill ~0 ~1 ~4 ~4 ~1 ~4 minecraft:oak_fence
fill ~0 ~1 ~8 ~4 ~1 ~8 minecraft:oak_fence
setblock ~4 ~1 ~5 minecraft:oak_fence
setblock ~4 ~1 ~7 minecraft:oak_fence
setblock ~4 ~1 ~6 minecraft:air
summon minecraft:villager ~2 ~1 ~7
setblock ~9 ~0 ~5 minecraft:farmland
setblock ~9 ~1 ~5 minecraft:wheat["growth"=4]
setblock ~9 ~0 ~6 minecraft:farmland
setblock ~9 ~1 ~6 minecraft:wheat["growth"=1]
setblock ~9 ~0 ~7 minecraft:farmland
setblock ~9 ~1 ~7 minecraft:wheat["growth"=1]
setblock ~10 ~0 ~5 minecraft:farmland
setblock ~10 ~1 ~5 minecraft:wheat["growth"=6]
setblock ~10 ~0 ~7 minecraft:farmland
setblock ~10 ~1 ~7 minecraft:wheat["growth"=0]
setblock ~11 ~0 ~5 minecraft:farmland
setblock ~11 ~1 ~5 minecraft:wheat["growth"=3]
setblock ~11 ~0 ~6 minecraft:farmland
setblock ~11 ~1 ~6 minecraft:wheat["growth"=6]
setblock ~11 ~0 ~7 minecraft:farmland
setblock ~11 ~1 ~7 minecraft:wheat["growth"=5]
setblock ~10 ~0 ~6 minecraft:water
setblock ~11 ~0 ~5 minecraft:grass_block
setblock ~11 ~1 ~5 minecraft:composter
fill ~8 ~1 ~4 ~12 ~1 ~4 minecraft:oak_fence
fill ~8 ~1 ~8 ~12 ~1 ~8 minecraft:oak_fence
setblock ~8 ~1 ~5 minecraft:oak_fence
setblock ~8 ~1 ~7 minecraft:oak_fence
setblock ~8 ~1 ~6 minecraft:air
summon minecraft:villager ~10 ~1 ~7
fill ~4 ~1 ~4 ~4 ~1 ~8 minecraft:oak_fence
fill ~8 ~1 ~4 ~8 ~1 ~8 minecraft:oak_fence
fill ~4 ~1 ~4 ~8 ~1 ~4 minecraft:oak_fence
fill ~4 ~1 ~8 ~8 ~1 ~8 minecraft:oak_fence
setblock ~4 ~1 ~6 minecraft:air
setblock ~8 ~1 ~6 minecraft:air
setblock ~6 ~1 ~4 minecraft:air
setblock ~6 ~1 ~8 minecraft:air
summon minecraft:villager ~6 ~1 ~6
setblock ~6 ~0 ~5 minecraft:hopper["facing_direction"=3]
setblock ~6 ~1 ~5 minecraft:rail
summon minecraft:hopper_minecart ~6 ~1 ~5
setblock ~6 ~0 ~7 minecraft:hopper["facing_direction"=2]
setblock ~6 ~1 ~7 minecraft:rail
summon minecraft:hopper_minecart ~6 ~1 ~7
setblock ~5 ~0 ~6 minecraft:hopper["facing_direction"=5]
setblock ~5 ~1 ~6 minecraft:rail
summon minecraft:hopper_minecart ~5 ~1 ~6
setblock ~7 ~0 ~6 minecraft:hopper["facing_direction"=4]
setblock ~7 ~1 ~6 minecraft:rail
summon minecraft:hopper_minecart ~7 ~1 ~6
setblock ~6 ~0 ~6 minecraft:hopper["facing_direction"=0]
setblock ~6 ~1 ~6 minecraft:rail
summon minecraft:hopper_minecart ~6 ~1 ~6
setblock ~6 ~-1 ~6 minecraft:hopper["facing_direction"=4]
setblock ~5 ~-1 ~6 minecraft:hopper["facing_direction"=4]
setblock ~4 ~-1 ~6 minecraft:hopper["facing_direction"=4]
setblock ~3 ~-1 ~6 minecraft:hopper["facing_direction"=4]
setblock ~2 ~-1 ~6 minecraft:hopper["facing_direction"=4]
setblock ~1 ~-1 ~6 minecraft:hopper["facing_direction"=4]
setblock ~0 ~-1 ~6 minecraft:hopper["facing_direction"=4]
setblock ~-1 ~-1 ~6 minecraft:hopper["facing_direction"=0]
setblock ~-1 ~-3 ~6 minecraft:chest
setblock ~-2 ~-3 ~6 minecraft:chest
setblock ~-1 ~-2 ~6 minecraft:hopper["facing_direction"=0]
setblock ~-1 ~-1 ~6 minecraft:hopper["facing_direction"=0]
tellraw @s {"rawtext":[{"text":"§aDone."}]}
