/**
 * The End's tree species, and how to grow one.
 *
 * Generated by tools/treegen/build.py - do not edit by hand.
 *
 * Every region of the map has its own wood, and a region's trees are the
 * fastest way to tell it apart from the one next door: the Bonespire's pale
 * spires and the Glowspore Basin's magenta caps read as different places from
 * a long way further off than a change of ground colour ever does.
 *
 * `growTree` is deliberately synchronous and bounded. It is called from the
 * painter, from the sky-island builder and from a sapling's growth pass, all
 * of which are already inside a `system.runJob`, so it must not yield and it
 * must not run long: one tree is at most a few hundred block writes.
 */

import { BlockPermutation } from "@minecraft/server";

export const SPECIES = {
  ender: {
    key: "ender",
    name: "Ender",
    biome: "verdant",
    shape: "round",
    log: "voidbound:ender_log",
    leaves: "voidbound:ender_leaves",
    sapling: "voidbound:ender_sapling",
    minHeight: 6,
    maxHeight: 10,
    radius: 3,
    hangs: "voidbound:ender_vines",
  },
  sporewood: {
    key: "sporewood",
    name: "Sporewood",
    biome: "glowspore",
    shape: "cap",
    log: "voidbound:sporewood_log",
    leaves: "voidbound:sporewood_leaves",
    sapling: "voidbound:sporewood_sapling",
    minHeight: 5,
    maxHeight: 9,
    radius: 4,
    hangs: "voidbound:spore_tendril",
  },
  bonewood: {
    key: "bonewood",
    name: "Bonewood",
    biome: "bonespire",
    shape: "spire",
    log: "voidbound:bonewood_log",
    leaves: "voidbound:bonewood_leaves",
    sapling: "voidbound:bonewood_sapling",
    minHeight: 7,
    maxHeight: 13,
    radius: 3,
    hangs: "voidbound:frost_icicle",
  },
  shardwood: {
    key: "shardwood",
    name: "Shardwood",
    biome: "crystalline",
    shape: "spire",
    log: "voidbound:shardwood_log",
    leaves: "voidbound:shardwood_leaves",
    sapling: "voidbound:shardwood_sapling",
    minHeight: 6,
    maxHeight: 11,
    radius: 3,
    hangs: "voidbound:crystal_dripstone",
  },
  cinderwood: {
    key: "cinderwood",
    name: "Cinderwood",
    biome: "ashen",
    shape: "flat",
    log: "voidbound:cinderwood_log",
    leaves: "voidbound:cinderwood_leaves",
    sapling: "voidbound:cinderwood_sapling",
    minHeight: 5,
    maxHeight: 9,
    radius: 4,
    hangs: "voidbound:ash_stalactite",
  },
  auralwood: {
    key: "auralwood",
    name: "Auralwood",
    biome: "aurora",
    shape: "weeping",
    log: "voidbound:auralwood_log",
    leaves: "voidbound:auralwood_leaves",
    sapling: "voidbound:auralwood_sapling",
    minHeight: 6,
    maxHeight: 11,
    radius: 4,
    hangs: "voidbound:aurora_veil",
  },
  voidwood: {
    key: "voidwood",
    name: "Voidwood",
    biome: "barrens",
    shape: "weeping",
    log: "voidbound:voidwood_log",
    leaves: "voidbound:voidwood_leaves",
    sapling: "voidbound:voidwood_sapling",
    minHeight: 5,
    maxHeight: 10,
    radius: 3,
    hangs: "voidbound:ender_vines",
  },
};

/** The species a region grows, by biome id. */
export const BY_BIOME = Object.fromEntries(
  Object.values(SPECIES).map((species) => [species.biome, species])
);

/** Look a species up from the sapling block a player placed. */
export const BY_SAPLING = Object.fromEntries(
  Object.values(SPECIES).map((species) => [species.sapling, species])
);

/** Blocks a trunk or canopy may grow through. Anything else stops it. */
const PASSABLE = new Set([
  "minecraft:air",
  ...Object.values(SPECIES).map((species) => species.sapling),
  ...Object.values(SPECIES).map((species) => species.leaves),
  "voidbound:ender_bush",
  "voidbound:voidbloom",
  "voidbound:lumen_bulb",
  "voidbound:sporelight_fungus",
  "voidbound:pale_shroom",
  "voidbound:frost_bloom",
]);

const permutations = new Map();
function permutation(id) {
  if (!permutations.has(id)) {
    try {
      permutations.set(id, BlockPermutation.resolve(id));
    } catch {
      permutations.set(id, undefined);
    }
  }
  return permutations.get(id);
}

function passable(dimension, x, y, z) {
  try {
    const block = dimension.getBlock({ x, y, z });
    return block ? PASSABLE.has(block.typeId) : false;
  } catch {
    return false;
  }
}

function put(dimension, x, y, z, id) {
  const wanted = permutation(id);
  if (!wanted) return false;
  try {
    const block = dimension.getBlock({ x, y, z });
    if (!block || !PASSABLE.has(block.typeId)) return false;
    block.setPermutation(wanted);
    return true;
  } catch {
    return false;
  }
}

/**
 * The canopy discs for a species, as (dy, radius) pairs.
 *
 * The shape is the species' whole silhouette, so this is where a Bonewood
 * stops being a recoloured Ender tree.
 */
function canopy(species, height, rng) {
  const r = species.radius;
  switch (species.shape) {
    case "cap":
      // One wide mushroom cap, and nothing under it.
      return [
        { dy: 0, radius: r + 0.6 },
        { dy: 1, radius: r - 0.4 },
      ];
    case "spire":
      // A conifer: wide at the bottom, a point at the top.
      return [
        { dy: -3, radius: r },
        { dy: -2, radius: r - 0.5 },
        { dy: -1, radius: r - 1.0 },
        { dy: 0, radius: r - 1.4 },
        { dy: 1, radius: 0.8 },
      ];
    case "flat":
      // A low umbrella, the way a thing that grows in ash grows.
      return [
        { dy: -1, radius: r + 0.4 },
        { dy: 0, radius: r },
      ];
    case "weeping":
      return [
        { dy: -1, radius: r },
        { dy: 0, radius: r - 0.2 },
        { dy: 1, radius: r - 1.4 },
      ];
    default:
      return [
        { dy: -1, radius: r - 0.4 },
        { dy: 0, radius: r },
        { dy: 1, radius: r - 1.2 },
      ];
  }
}

/**
 * Grow one tree with its base at `base`.
 *
 * @returns true if a tree was actually placed. False means the spot could not
 * hold one - no headroom, or something in the way - and the caller should
 * leave whatever was there alone rather than deleting it into nothing.
 */
export function growTree(dimension, base, species, rng) {
  const height = rng.int(species.minHeight, species.maxHeight);

  // Headroom first. A tree that grows into a ceiling looks like a bug.
  for (let dy = 1; dy <= height + 2; dy++) {
    if (!passable(dimension, base.x, base.y + dy, base.z)) return false;
  }

  // Trunk, with one lean, so a grove is not a row of posts. A mushroom cap
  // grows dead straight - a leaning stalk reads as damage, not character.
  const straight = species.shape === "cap";
  const leanAt = straight ? height + 1 : rng.int(2, Math.max(2, height - 2));
  const leanX = rng.chance(0.5) ? (rng.chance(0.5) ? 1 : -1) : 0;
  const leanZ = leanX === 0 ? (rng.chance(0.5) ? 1 : -1) : 0;

  let tipX = base.x;
  let tipZ = base.z;
  for (let dy = 0; dy < height; dy++) {
    if (dy === leanAt) {
      // Bridge the step, or the trunk breaks into a floating diagonal.
      put(dimension, tipX, base.y + dy, tipZ, species.log);
      tipX += leanX;
      tipZ += leanZ;
    }
    put(dimension, tipX, base.y + dy, tipZ, species.log);
  }

  const top = base.y + height;
  for (const disc of canopy(species, height, rng)) {
    const radius = disc.radius;
    const reach = Math.ceil(radius);
    for (let dx = -reach; dx <= reach; dx++) {
      for (let dz = -reach; dz <= reach; dz++) {
        const distance = Math.hypot(dx, dz);
        if (distance > radius) continue;
        // Thin the corners, so the crown is not a cylinder.
        if (distance > radius - 0.9 && rng.chance(0.45)) continue;
        put(dimension, tipX + dx, top + disc.dy, tipZ + dz, species.leaves);
      }
    }
  }

  // A cap sits on its stalk; everything else closes over the trunk.
  if (species.shape === "cap") {
    put(dimension, tipX, top - 1, tipZ, species.log);
  }

  // What trails off the crown. This is most of why a canopy reads as alive
  // rather than as a lump of leaves on a stick.
  if (species.hangs) {
    const reach = Math.ceil(species.radius);
    for (let dx = -reach; dx <= reach; dx++) {
      for (let dz = -reach; dz <= reach; dz++) {
        if (Math.hypot(dx, dz) < species.radius - 1.2) continue;
        if (!rng.chance(0.3)) continue;
        const length = rng.int(1, 4);
        for (let down = 1; down <= length; down++) {
          if (!put(dimension, tipX + dx, top - 1 - down, tipZ + dz, species.hangs)) {
            break;
          }
        }
      }
    }
  }

  return true;
}
