/**
 * Attack and hurt clips for the Eternal End roster.
 *
 * Generated by tools/mobgen/build.py - do not edit by hand. Merged
 * into the clip table in mobActions.js, which is what plays them.
 */

export const ETERNAL_END_CLIPS = [
  ["eternal_end:void_dragon", {
    attack: "animation.eternal_end.void_dragon.attack",
    hurt: "animation.eternal_end.void_dragon.hurt",
  }],
  ["eternal_end:ender_overlord", {
    attack: "animation.eternal_end.ender_overlord.attack",
    hurt: "animation.eternal_end.ender_overlord.hurt",
  }],
  ["eternal_end:end_king", {
    attack: "animation.eternal_end.end_king.attack",
    hurt: "animation.eternal_end.end_king.hurt",
  }],
  ["eternal_end:void_stalker", {
    attack: "animation.eternal_end.void_stalker.attack",
    hurt: "animation.eternal_end.void_stalker.hurt",
  }],
  ["eternal_end:endermite_hive", {
    attack: "animation.eternal_end.endermite_hive.attack",
    hurt: "animation.eternal_end.endermite_hive.hurt",
  }],
  ["eternal_end:purpur_golem", {
    attack: "animation.eternal_end.purpur_golem.attack",
    hurt: "animation.eternal_end.purpur_golem.hurt",
  }],
  ["eternal_end:shulker_beast", {
    attack: "animation.eternal_end.shulker_beast.attack",
    hurt: "animation.eternal_end.shulker_beast.hurt",
  }],
  ["eternal_end:void_wisp", {
    attack: "animation.eternal_end.void_wisp.attack",
    hurt: "animation.eternal_end.void_wisp.hurt",
  }],
  ["eternal_end:end_spider", {
    attack: "animation.eternal_end.end_spider.attack",
    hurt: "animation.eternal_end.end_spider.hurt",
  }],
  ["eternal_end:corrupted_enderman", {
    attack: "animation.eternal_end.corrupted_enderman.attack",
    hurt: "animation.eternal_end.corrupted_enderman.hurt",
  }],
  ["eternal_end:chorus_fiend", {
    attack: "animation.eternal_end.chorus_fiend.attack",
    hurt: "animation.eternal_end.chorus_fiend.hurt",
  }],
  ["eternal_end:void_slime", {
    attack: "animation.eternal_end.void_slime.attack",
    hurt: "animation.eternal_end.void_slime.hurt",
  }],
  ["eternal_end:teleporter", {
    attack: "animation.eternal_end.teleporter.attack",
    hurt: "animation.eternal_end.teleporter.hurt",
  }],
  ["eternal_end:end_crab", {
    attack: "animation.eternal_end.end_crab.attack",
    hurt: "animation.eternal_end.end_crab.hurt",
  }],
  ["eternal_end:obsidian_beast", {
    attack: "animation.eternal_end.obsidian_beast.attack",
    hurt: "animation.eternal_end.obsidian_beast.hurt",
  }],
  ["eternal_end:ender_deer", {
    attack: "animation.eternal_end.ender_deer.attack",
    hurt: "animation.eternal_end.ender_deer.hurt",
  }],
  ["eternal_end:chorus_cow", {
    attack: "animation.eternal_end.chorus_cow.attack",
    hurt: "animation.eternal_end.chorus_cow.hurt",
  }],
  ["eternal_end:void_hog", {
    attack: "animation.eternal_end.void_hog.attack",
    hurt: "animation.eternal_end.void_hog.hurt",
  }],
  ["eternal_end:sky_ray", {
    attack: "animation.eternal_end.sky_ray.attack",
    hurt: "animation.eternal_end.sky_ray.hurt",
  }],
  ["eternal_end:ender_bird", {
    attack: "animation.eternal_end.ender_bird.attack",
    hurt: "animation.eternal_end.ender_bird.hurt",
  }],
];
