"""
Owning one region of a shared language file.

`RP/texts/en_US.lang` is hand-written at the top and generated further down -
once by the mob generator, once by the tree generator - and both have to be
able to rewrite their own lines without touching each other's or the
hand-written ones. So each generator claims a region between a pair of markers
and this replaces exactly that, wherever in the file it happens to sit.
"""

from __future__ import annotations

import os


def start_marker(owner):
    return f"## >>> generated by tools/{owner} - do not edit inside this block"


def end_marker(owner):
    return f"## <<< end tools/{owner}"


def write_block(path, owner, lines):
    """Replace `owner`'s region of the file, appending it if it is not there."""
    existing = ""
    if os.path.exists(path):
        with open(path, encoding="utf-8") as handle:
            existing = handle.read()

    start = start_marker(owner)
    end = end_marker(owner)
    block = start + "\n" + "\n".join(lines).rstrip() + "\n" + end

    if start in existing and end in existing:
        head, remainder = existing.split(start, 1)
        _, tail = remainder.split(end, 1)
        updated = head + block + tail
    else:
        updated = existing.rstrip() + "\n\n" + block + "\n"

    with open(path, "w", encoding="utf-8") as handle:
        handle.write(updated)
