# Generated by tools/generate.js — do not hand-edit, regenerate instead.
tellraw @s {"rawtext":[{"text":"§aBuilding Iron Farm (4 levels)..."}]}
fill ~0 ~0 ~0 ~14 ~9 ~14 minecraft:cobblestone hollow
fill ~0 ~0 ~0 ~14 ~0 ~14 minecraft:stone_bricks
fill ~4 ~1 ~1 ~4 ~3 ~3 minecraft:cobblestone
fill ~1 ~1 ~4 ~3 ~3 ~4 minecraft:cobblestone
fill ~1 ~4 ~1 ~3 ~4 ~3 minecraft:cobblestone
setblock ~2 ~1 ~1 minecraft:bed["direction"=0,"head_piece_bit"=false]
setblock ~2 ~1 ~2 minecraft:bed["direction"=0,"head_piece_bit"=true]
setblock ~1 ~1 ~1 minecraft:torch
summon minecraft:villager ~2 ~1 ~1
fill ~10 ~1 ~1 ~10 ~3 ~3 minecraft:cobblestone
fill ~11 ~1 ~4 ~13 ~3 ~4 minecraft:cobblestone
fill ~11 ~4 ~1 ~13 ~4 ~3 minecraft:cobblestone
setblock ~12 ~1 ~1 minecraft:bed["direction"=0,"head_piece_bit"=false]
setblock ~12 ~1 ~2 minecraft:bed["direction"=0,"head_piece_bit"=true]
setblock ~11 ~1 ~1 minecraft:torch
summon minecraft:villager ~12 ~1 ~1
fill ~4 ~1 ~11 ~4 ~3 ~13 minecraft:cobblestone
fill ~1 ~1 ~10 ~3 ~3 ~10 minecraft:cobblestone
fill ~1 ~4 ~11 ~3 ~4 ~13 minecraft:cobblestone
setblock ~2 ~1 ~11 minecraft:bed["direction"=0,"head_piece_bit"=false]
setblock ~2 ~1 ~12 minecraft:bed["direction"=0,"head_piece_bit"=true]
setblock ~1 ~1 ~11 minecraft:torch
summon minecraft:villager ~2 ~1 ~11
fill ~10 ~1 ~11 ~10 ~3 ~13 minecraft:cobblestone
fill ~11 ~1 ~10 ~13 ~3 ~10 minecraft:cobblestone
fill ~11 ~4 ~11 ~13 ~4 ~13 minecraft:cobblestone
setblock ~12 ~1 ~11 minecraft:bed["direction"=0,"head_piece_bit"=false]
setblock ~12 ~1 ~12 minecraft:bed["direction"=0,"head_piece_bit"=true]
setblock ~11 ~1 ~11 minecraft:torch
summon minecraft:villager ~12 ~1 ~11
fill ~1 ~4 ~1 ~13 ~4 ~13 minecraft:cobblestone
setblock ~7 ~4 ~7 minecraft:air
fill ~10 ~1 ~6 ~10 ~3 ~8 minecraft:glass
fill ~12 ~1 ~6 ~12 ~3 ~8 minecraft:glass
fill ~10 ~1 ~6 ~12 ~3 ~6 minecraft:glass
fill ~10 ~1 ~8 ~12 ~3 ~8 minecraft:glass
summon minecraft:zombie ~11 ~1 ~7
fill ~1 ~5 ~1 ~13 ~5 ~13 minecraft:stone_bricks
setblock ~7 ~5 ~7 minecraft:air
setblock ~3 ~6 ~3 minecraft:water
setblock ~11 ~6 ~3 minecraft:water
setblock ~3 ~6 ~11 minecraft:water
setblock ~11 ~6 ~11 minecraft:water
setblock ~7 ~6 ~3 minecraft:water
setblock ~7 ~6 ~11 minecraft:water
setblock ~3 ~6 ~7 minecraft:water
setblock ~11 ~6 ~7 minecraft:water
fill ~4 ~1 ~6 ~13 ~2 ~6 minecraft:cobblestone
fill ~4 ~1 ~8 ~13 ~2 ~8 minecraft:cobblestone
fill ~4 ~1 ~7 ~4 ~2 ~7 minecraft:cobblestone
fill ~5 ~0 ~7 ~13 ~0 ~7 minecraft:magma
setblock ~5 ~1 ~7 minecraft:water
setblock ~14 ~0 ~7 minecraft:hopper["facing_direction"=5]
setblock ~0 ~2 ~7 minecraft:sea_lantern
setblock ~14 ~2 ~7 minecraft:sea_lantern
setblock ~7 ~2 ~0 minecraft:sea_lantern
setblock ~7 ~2 ~14 minecraft:sea_lantern
setblock ~0 ~7 ~7 minecraft:sea_lantern
setblock ~14 ~7 ~7 minecraft:sea_lantern
setblock ~7 ~7 ~0 minecraft:sea_lantern
setblock ~7 ~7 ~14 minecraft:sea_lantern
fill ~0 ~12 ~0 ~14 ~21 ~14 minecraft:cobblestone hollow
fill ~0 ~12 ~0 ~14 ~12 ~14 minecraft:stone_bricks
fill ~4 ~13 ~1 ~4 ~15 ~3 minecraft:cobblestone
fill ~1 ~13 ~4 ~3 ~15 ~4 minecraft:cobblestone
fill ~1 ~16 ~1 ~3 ~16 ~3 minecraft:cobblestone
setblock ~2 ~13 ~1 minecraft:bed["direction"=0,"head_piece_bit"=false]
setblock ~2 ~13 ~2 minecraft:bed["direction"=0,"head_piece_bit"=true]
setblock ~1 ~13 ~1 minecraft:torch
summon minecraft:villager ~2 ~13 ~1
fill ~10 ~13 ~1 ~10 ~15 ~3 minecraft:cobblestone
fill ~11 ~13 ~4 ~13 ~15 ~4 minecraft:cobblestone
fill ~11 ~16 ~1 ~13 ~16 ~3 minecraft:cobblestone
setblock ~12 ~13 ~1 minecraft:bed["direction"=0,"head_piece_bit"=false]
setblock ~12 ~13 ~2 minecraft:bed["direction"=0,"head_piece_bit"=true]
setblock ~11 ~13 ~1 minecraft:torch
summon minecraft:villager ~12 ~13 ~1
fill ~4 ~13 ~11 ~4 ~15 ~13 minecraft:cobblestone
fill ~1 ~13 ~10 ~3 ~15 ~10 minecraft:cobblestone
fill ~1 ~16 ~11 ~3 ~16 ~13 minecraft:cobblestone
setblock ~2 ~13 ~11 minecraft:bed["direction"=0,"head_piece_bit"=false]
setblock ~2 ~13 ~12 minecraft:bed["direction"=0,"head_piece_bit"=true]
setblock ~1 ~13 ~11 minecraft:torch
summon minecraft:villager ~2 ~13 ~11
fill ~10 ~13 ~11 ~10 ~15 ~13 minecraft:cobblestone
fill ~11 ~13 ~10 ~13 ~15 ~10 minecraft:cobblestone
fill ~11 ~16 ~11 ~13 ~16 ~13 minecraft:cobblestone
setblock ~12 ~13 ~11 minecraft:bed["direction"=0,"head_piece_bit"=false]
setblock ~12 ~13 ~12 minecraft:bed["direction"=0,"head_piece_bit"=true]
setblock ~11 ~13 ~11 minecraft:torch
summon minecraft:villager ~12 ~13 ~11
fill ~1 ~16 ~1 ~13 ~16 ~13 minecraft:cobblestone
setblock ~7 ~16 ~7 minecraft:air
fill ~10 ~13 ~6 ~10 ~15 ~8 minecraft:glass
fill ~12 ~13 ~6 ~12 ~15 ~8 minecraft:glass
fill ~10 ~13 ~6 ~12 ~15 ~6 minecraft:glass
fill ~10 ~13 ~8 ~12 ~15 ~8 minecraft:glass
summon minecraft:zombie ~11 ~13 ~7
fill ~1 ~17 ~1 ~13 ~17 ~13 minecraft:stone_bricks
setblock ~7 ~17 ~7 minecraft:air
setblock ~3 ~18 ~3 minecraft:water
setblock ~11 ~18 ~3 minecraft:water
setblock ~3 ~18 ~11 minecraft:water
setblock ~11 ~18 ~11 minecraft:water
setblock ~7 ~18 ~3 minecraft:water
setblock ~7 ~18 ~11 minecraft:water
setblock ~3 ~18 ~7 minecraft:water
setblock ~11 ~18 ~7 minecraft:water
fill ~4 ~13 ~6 ~13 ~14 ~6 minecraft:cobblestone
fill ~4 ~13 ~8 ~13 ~14 ~8 minecraft:cobblestone
fill ~4 ~13 ~7 ~4 ~14 ~7 minecraft:cobblestone
fill ~5 ~12 ~7 ~13 ~12 ~7 minecraft:magma
setblock ~5 ~13 ~7 minecraft:water
setblock ~14 ~12 ~7 minecraft:hopper["facing_direction"=5]
setblock ~0 ~14 ~7 minecraft:sea_lantern
setblock ~14 ~14 ~7 minecraft:sea_lantern
setblock ~7 ~14 ~0 minecraft:sea_lantern
setblock ~7 ~14 ~14 minecraft:sea_lantern
setblock ~0 ~19 ~7 minecraft:sea_lantern
setblock ~14 ~19 ~7 minecraft:sea_lantern
setblock ~7 ~19 ~0 minecraft:sea_lantern
setblock ~7 ~19 ~14 minecraft:sea_lantern
fill ~0 ~24 ~0 ~14 ~33 ~14 minecraft:cobblestone hollow
fill ~0 ~24 ~0 ~14 ~24 ~14 minecraft:stone_bricks
fill ~4 ~25 ~1 ~4 ~27 ~3 minecraft:cobblestone
fill ~1 ~25 ~4 ~3 ~27 ~4 minecraft:cobblestone
fill ~1 ~28 ~1 ~3 ~28 ~3 minecraft:cobblestone
setblock ~2 ~25 ~1 minecraft:bed["direction"=0,"head_piece_bit"=false]
setblock ~2 ~25 ~2 minecraft:bed["direction"=0,"head_piece_bit"=true]
setblock ~1 ~25 ~1 minecraft:torch
summon minecraft:villager ~2 ~25 ~1
fill ~10 ~25 ~1 ~10 ~27 ~3 minecraft:cobblestone
fill ~11 ~25 ~4 ~13 ~27 ~4 minecraft:cobblestone
fill ~11 ~28 ~1 ~13 ~28 ~3 minecraft:cobblestone
setblock ~12 ~25 ~1 minecraft:bed["direction"=0,"head_piece_bit"=false]
setblock ~12 ~25 ~2 minecraft:bed["direction"=0,"head_piece_bit"=true]
setblock ~11 ~25 ~1 minecraft:torch
summon minecraft:villager ~12 ~25 ~1
fill ~4 ~25 ~11 ~4 ~27 ~13 minecraft:cobblestone
fill ~1 ~25 ~10 ~3 ~27 ~10 minecraft:cobblestone
fill ~1 ~28 ~11 ~3 ~28 ~13 minecraft:cobblestone
setblock ~2 ~25 ~11 minecraft:bed["direction"=0,"head_piece_bit"=false]
setblock ~2 ~25 ~12 minecraft:bed["direction"=0,"head_piece_bit"=true]
setblock ~1 ~25 ~11 minecraft:torch
summon minecraft:villager ~2 ~25 ~11
fill ~10 ~25 ~11 ~10 ~27 ~13 minecraft:cobblestone
fill ~11 ~25 ~10 ~13 ~27 ~10 minecraft:cobblestone
fill ~11 ~28 ~11 ~13 ~28 ~13 minecraft:cobblestone
setblock ~12 ~25 ~11 minecraft:bed["direction"=0,"head_piece_bit"=false]
setblock ~12 ~25 ~12 minecraft:bed["direction"=0,"head_piece_bit"=true]
setblock ~11 ~25 ~11 minecraft:torch
summon minecraft:villager ~12 ~25 ~11
fill ~1 ~28 ~1 ~13 ~28 ~13 minecraft:cobblestone
setblock ~7 ~28 ~7 minecraft:air
fill ~10 ~25 ~6 ~10 ~27 ~8 minecraft:glass
fill ~12 ~25 ~6 ~12 ~27 ~8 minecraft:glass
fill ~10 ~25 ~6 ~12 ~27 ~6 minecraft:glass
fill ~10 ~25 ~8 ~12 ~27 ~8 minecraft:glass
summon minecraft:zombie ~11 ~25 ~7
fill ~1 ~29 ~1 ~13 ~29 ~13 minecraft:stone_bricks
setblock ~7 ~29 ~7 minecraft:air
setblock ~3 ~30 ~3 minecraft:water
setblock ~11 ~30 ~3 minecraft:water
setblock ~3 ~30 ~11 minecraft:water
setblock ~11 ~30 ~11 minecraft:water
setblock ~7 ~30 ~3 minecraft:water
setblock ~7 ~30 ~11 minecraft:water
setblock ~3 ~30 ~7 minecraft:water
setblock ~11 ~30 ~7 minecraft:water
fill ~4 ~25 ~6 ~13 ~26 ~6 minecraft:cobblestone
fill ~4 ~25 ~8 ~13 ~26 ~8 minecraft:cobblestone
fill ~4 ~25 ~7 ~4 ~26 ~7 minecraft:cobblestone
fill ~5 ~24 ~7 ~13 ~24 ~7 minecraft:magma
setblock ~5 ~25 ~7 minecraft:water
setblock ~14 ~24 ~7 minecraft:hopper["facing_direction"=5]
setblock ~0 ~26 ~7 minecraft:sea_lantern
setblock ~14 ~26 ~7 minecraft:sea_lantern
setblock ~7 ~26 ~0 minecraft:sea_lantern
setblock ~7 ~26 ~14 minecraft:sea_lantern
setblock ~0 ~31 ~7 minecraft:sea_lantern
setblock ~14 ~31 ~7 minecraft:sea_lantern
setblock ~7 ~31 ~0 minecraft:sea_lantern
setblock ~7 ~31 ~14 minecraft:sea_lantern
fill ~0 ~36 ~0 ~14 ~45 ~14 minecraft:cobblestone hollow
fill ~0 ~36 ~0 ~14 ~36 ~14 minecraft:stone_bricks
fill ~4 ~37 ~1 ~4 ~39 ~3 minecraft:cobblestone
fill ~1 ~37 ~4 ~3 ~39 ~4 minecraft:cobblestone
fill ~1 ~40 ~1 ~3 ~40 ~3 minecraft:cobblestone
setblock ~2 ~37 ~1 minecraft:bed["direction"=0,"head_piece_bit"=false]
setblock ~2 ~37 ~2 minecraft:bed["direction"=0,"head_piece_bit"=true]
setblock ~1 ~37 ~1 minecraft:torch
summon minecraft:villager ~2 ~37 ~1
fill ~10 ~37 ~1 ~10 ~39 ~3 minecraft:cobblestone
fill ~11 ~37 ~4 ~13 ~39 ~4 minecraft:cobblestone
fill ~11 ~40 ~1 ~13 ~40 ~3 minecraft:cobblestone
setblock ~12 ~37 ~1 minecraft:bed["direction"=0,"head_piece_bit"=false]
setblock ~12 ~37 ~2 minecraft:bed["direction"=0,"head_piece_bit"=true]
setblock ~11 ~37 ~1 minecraft:torch
summon minecraft:villager ~12 ~37 ~1
fill ~4 ~37 ~11 ~4 ~39 ~13 minecraft:cobblestone
fill ~1 ~37 ~10 ~3 ~39 ~10 minecraft:cobblestone
fill ~1 ~40 ~11 ~3 ~40 ~13 minecraft:cobblestone
setblock ~2 ~37 ~11 minecraft:bed["direction"=0,"head_piece_bit"=false]
setblock ~2 ~37 ~12 minecraft:bed["direction"=0,"head_piece_bit"=true]
setblock ~1 ~37 ~11 minecraft:torch
summon minecraft:villager ~2 ~37 ~11
fill ~10 ~37 ~11 ~10 ~39 ~13 minecraft:cobblestone
fill ~11 ~37 ~10 ~13 ~39 ~10 minecraft:cobblestone
fill ~11 ~40 ~11 ~13 ~40 ~13 minecraft:cobblestone
setblock ~12 ~37 ~11 minecraft:bed["direction"=0,"head_piece_bit"=false]
setblock ~12 ~37 ~12 minecraft:bed["direction"=0,"head_piece_bit"=true]
setblock ~11 ~37 ~11 minecraft:torch
summon minecraft:villager ~12 ~37 ~11
fill ~1 ~40 ~1 ~13 ~40 ~13 minecraft:cobblestone
setblock ~7 ~40 ~7 minecraft:air
fill ~10 ~37 ~6 ~10 ~39 ~8 minecraft:glass
fill ~12 ~37 ~6 ~12 ~39 ~8 minecraft:glass
fill ~10 ~37 ~6 ~12 ~39 ~6 minecraft:glass
fill ~10 ~37 ~8 ~12 ~39 ~8 minecraft:glass
summon minecraft:zombie ~11 ~37 ~7
fill ~1 ~41 ~1 ~13 ~41 ~13 minecraft:stone_bricks
setblock ~7 ~41 ~7 minecraft:air
setblock ~3 ~42 ~3 minecraft:water
setblock ~11 ~42 ~3 minecraft:water
setblock ~3 ~42 ~11 minecraft:water
setblock ~11 ~42 ~11 minecraft:water
setblock ~7 ~42 ~3 minecraft:water
setblock ~7 ~42 ~11 minecraft:water
setblock ~3 ~42 ~7 minecraft:water
setblock ~11 ~42 ~7 minecraft:water
fill ~4 ~37 ~6 ~13 ~38 ~6 minecraft:cobblestone
fill ~4 ~37 ~8 ~13 ~38 ~8 minecraft:cobblestone
fill ~4 ~37 ~7 ~4 ~38 ~7 minecraft:cobblestone
fill ~5 ~36 ~7 ~13 ~36 ~7 minecraft:magma
setblock ~5 ~37 ~7 minecraft:water
setblock ~14 ~36 ~7 minecraft:hopper["facing_direction"=5]
setblock ~0 ~38 ~7 minecraft:sea_lantern
setblock ~14 ~38 ~7 minecraft:sea_lantern
setblock ~7 ~38 ~0 minecraft:sea_lantern
setblock ~7 ~38 ~14 minecraft:sea_lantern
setblock ~0 ~43 ~7 minecraft:sea_lantern
setblock ~14 ~43 ~7 minecraft:sea_lantern
setblock ~7 ~43 ~0 minecraft:sea_lantern
setblock ~7 ~43 ~14 minecraft:sea_lantern
setblock ~15 ~-2 ~7 minecraft:chest
setblock ~16 ~-2 ~7 minecraft:chest
setblock ~15 ~-1 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~0 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~1 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~2 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~3 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~4 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~5 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~6 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~7 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~8 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~9 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~10 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~11 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~12 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~13 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~14 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~15 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~16 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~17 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~18 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~19 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~20 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~21 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~22 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~23 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~24 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~25 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~26 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~27 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~28 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~29 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~30 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~31 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~32 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~33 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~34 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~35 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~36 ~7 minecraft:hopper["facing_direction"=0]
tellraw @s {"rawtext":[{"text":"§aDone."}]}
