# Generated by tools/generate.js — do not hand-edit, regenerate instead.
tellraw @s {"rawtext":[{"text":"§aBuilding Iron Farm (1 level)..."}]}
fill ~0 ~0 ~0 ~14 ~9 ~14 minecraft:cobblestone hollow
fill ~0 ~0 ~0 ~14 ~0 ~14 minecraft:stone_bricks
fill ~4 ~1 ~1 ~4 ~3 ~3 minecraft:cobblestone
fill ~1 ~1 ~4 ~3 ~3 ~4 minecraft:cobblestone
fill ~1 ~4 ~1 ~3 ~4 ~3 minecraft:cobblestone
setblock ~2 ~1 ~1 minecraft:bed["direction"=0,"head_piece_bit"=false]
setblock ~2 ~1 ~2 minecraft:bed["direction"=0,"head_piece_bit"=true]
setblock ~1 ~1 ~1 minecraft:torch
summon minecraft:villager ~2 ~1 ~1
fill ~10 ~1 ~1 ~10 ~3 ~3 minecraft:cobblestone
fill ~11 ~1 ~4 ~13 ~3 ~4 minecraft:cobblestone
fill ~11 ~4 ~1 ~13 ~4 ~3 minecraft:cobblestone
setblock ~12 ~1 ~1 minecraft:bed["direction"=0,"head_piece_bit"=false]
setblock ~12 ~1 ~2 minecraft:bed["direction"=0,"head_piece_bit"=true]
setblock ~11 ~1 ~1 minecraft:torch
summon minecraft:villager ~12 ~1 ~1
fill ~4 ~1 ~11 ~4 ~3 ~13 minecraft:cobblestone
fill ~1 ~1 ~10 ~3 ~3 ~10 minecraft:cobblestone
fill ~1 ~4 ~11 ~3 ~4 ~13 minecraft:cobblestone
setblock ~2 ~1 ~11 minecraft:bed["direction"=0,"head_piece_bit"=false]
setblock ~2 ~1 ~12 minecraft:bed["direction"=0,"head_piece_bit"=true]
setblock ~1 ~1 ~11 minecraft:torch
summon minecraft:villager ~2 ~1 ~11
fill ~10 ~1 ~11 ~10 ~3 ~13 minecraft:cobblestone
fill ~11 ~1 ~10 ~13 ~3 ~10 minecraft:cobblestone
fill ~11 ~4 ~11 ~13 ~4 ~13 minecraft:cobblestone
setblock ~12 ~1 ~11 minecraft:bed["direction"=0,"head_piece_bit"=false]
setblock ~12 ~1 ~12 minecraft:bed["direction"=0,"head_piece_bit"=true]
setblock ~11 ~1 ~11 minecraft:torch
summon minecraft:villager ~12 ~1 ~11
fill ~1 ~4 ~1 ~13 ~4 ~13 minecraft:cobblestone
setblock ~7 ~4 ~7 minecraft:air
fill ~10 ~1 ~6 ~10 ~3 ~8 minecraft:glass
fill ~12 ~1 ~6 ~12 ~3 ~8 minecraft:glass
fill ~10 ~1 ~6 ~12 ~3 ~6 minecraft:glass
fill ~10 ~1 ~8 ~12 ~3 ~8 minecraft:glass
summon minecraft:zombie ~11 ~1 ~7
fill ~1 ~5 ~1 ~13 ~5 ~13 minecraft:stone_bricks
setblock ~7 ~5 ~7 minecraft:air
setblock ~3 ~6 ~3 minecraft:water
setblock ~11 ~6 ~3 minecraft:water
setblock ~3 ~6 ~11 minecraft:water
setblock ~11 ~6 ~11 minecraft:water
setblock ~7 ~6 ~3 minecraft:water
setblock ~7 ~6 ~11 minecraft:water
setblock ~3 ~6 ~7 minecraft:water
setblock ~11 ~6 ~7 minecraft:water
fill ~4 ~1 ~6 ~13 ~2 ~6 minecraft:cobblestone
fill ~4 ~1 ~8 ~13 ~2 ~8 minecraft:cobblestone
fill ~4 ~1 ~7 ~4 ~2 ~7 minecraft:cobblestone
fill ~5 ~0 ~7 ~13 ~0 ~7 minecraft:magma
setblock ~5 ~1 ~7 minecraft:water
setblock ~14 ~0 ~7 minecraft:hopper["facing_direction"=5]
setblock ~0 ~2 ~7 minecraft:sea_lantern
setblock ~14 ~2 ~7 minecraft:sea_lantern
setblock ~7 ~2 ~0 minecraft:sea_lantern
setblock ~7 ~2 ~14 minecraft:sea_lantern
setblock ~0 ~7 ~7 minecraft:sea_lantern
setblock ~14 ~7 ~7 minecraft:sea_lantern
setblock ~7 ~7 ~0 minecraft:sea_lantern
setblock ~7 ~7 ~14 minecraft:sea_lantern
setblock ~15 ~-2 ~7 minecraft:chest
setblock ~16 ~-2 ~7 minecraft:chest
setblock ~15 ~-1 ~7 minecraft:hopper["facing_direction"=0]
setblock ~15 ~0 ~7 minecraft:hopper["facing_direction"=0]
tellraw @s {"rawtext":[{"text":"§aDone."}]}
