/**
 * The tree species, one per region.
 *
 * Generated by tools/gen_trees.py alongside the blocks and the
 * textures, so what grows in a region and what was painted for it
 * are the same tree by construction rather than by discipline.
 */

export const TREES = {
  verdant: {
    log: "voidbound:verdant_log",
    leaves: "voidbound:verdant_leaves",
    sapling: "voidbound:verdant_sapling",
    canopy: "dome",
    height: [6, 9],
  },
  bonespire: {
    log: "voidbound:bonespire_log",
    leaves: "voidbound:bonespire_leaves",
    sapling: "voidbound:bonespire_sapling",
    canopy: "spire",
    height: [8, 13],
  },
  glowspore: {
    log: "voidbound:glowspore_log",
    leaves: "voidbound:glowspore_leaves",
    sapling: "voidbound:glowspore_sapling",
    canopy: "parasol",
    height: [5, 8],
  },
  crystalline: {
    log: "voidbound:crystalline_log",
    leaves: "voidbound:crystalline_leaves",
    sapling: "voidbound:crystalline_sapling",
    canopy: "cluster",
    height: [6, 10],
  },
  aurora: {
    log: "voidbound:aurora_log",
    leaves: "voidbound:aurora_leaves",
    sapling: "voidbound:aurora_sapling",
    canopy: "weeping",
    height: [7, 11],
  },
  ashen: {
    log: "voidbound:ashen_log",
    leaves: "voidbound:ashen_leaves",
    sapling: "voidbound:ashen_sapling",
    canopy: "scrub",
    height: [4, 7],
  },
};
