import { mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { generateIronFarm, MAX_LEVELS as IRON_MAX } from "./ironFarmLayout.js";
import { generateCropFarm, MAX_LEVELS as CROP_MAX } from "./cropFarmLayout.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const BP_FUNCTIONS = join(__dirname, "..", "BP", "functions");

function writeFunction(subdir, name, header, lines) {
  const dir = join(BP_FUNCTIONS, subdir);
  mkdirSync(dir, { recursive: true });
  const content = [
    `# Generated by tools/generate.js — do not hand-edit, regenerate instead.`,
    `tellraw @s {"rawtext":[{"text":"§a${header}"}]}`,
    ...lines,
    `tellraw @s {"rawtext":[{"text":"§aDone."}]}`,
    "",
  ].join("\n");
  writeFileSync(join(dir, `${name}.mcfunction`), content, "utf8");
  return lines.length;
}

let totalLines = 0;
for (let levels = 1; levels <= IRON_MAX; levels++) {
  const lines = generateIronFarm(levels);
  const n = writeFunction("iron_farm", `level${levels}`, `Building Iron Farm (${levels} level${levels > 1 ? "s" : ""})...`, lines);
  totalLines += n;
  console.log(`iron_farm/level${levels}.mcfunction: ${n} commands`);
}

for (let levels = 1; levels <= CROP_MAX; levels++) {
  const lines = generateCropFarm(levels);
  const n = writeFunction("crop_farm", `level${levels}`, `Building Auto Crop Farm (${levels} level${levels > 1 ? "s" : ""})...`, lines);
  totalLines += n;
  console.log(`crop_farm/level${levels}.mcfunction: ${n} commands`);
}

console.log(`\nTotal commands generated: ${totalLines}`);
