#!/usr/bin/env python3
"""
Hand-authored 16x16 item sprites with automatic Minecraft-style shading.

Earlier passes drew icons with PIL primitives (ellipses, polygons) which is
why they read as soft blobs rather than item art: real Minecraft icons are
deliberate pixel art with a hard 1px dark border, a light source at the top
left, and only three or four tones per material.

Each icon here is a 16x16 mask. `shade()` then does the work every Minecraft
item texture does:

  * any body pixel touching empty space becomes the dark outline
  * interior pixels ramp from highlight (top-left) to shadow (bottom-right)
  * nothing is anti-aliased - every pixel is one of four exact tones

Mask characters:
    '.'  empty / transparent
    'X'  primary material
    'A'  accent material (second colour ramp)
    'B'  third material - handles/straps/wood
    'o'  flat glow, drawn at full brightness with no shading
"""
from PIL import Image

S = 16


def ramp(rgb):
    """outline, shadow, base, highlight - the four tones a Minecraft item
    texture is generally built from."""
    r, g, b = rgb[:3]

    def m(f, lift=0):
        return (
            max(0, min(255, int(r * f) + lift)),
            max(0, min(255, int(g * f) + lift)),
            max(0, min(255, int(b * f) + lift)),
            255,
        )

    return m(0.34), m(0.68), m(1.0), m(1.28, 12)


def parse(mask):
    rows = [r for r in mask.strip("\n").split("\n")]
    grid = [list(r.ljust(S, ".")[:S]) for r in rows]
    while len(grid) < S:
        grid.append(list("." * S))
    return grid[:S]


def shade(mask, primary, accent=None, third=None, glow=(255, 240, 180)):
    """Renders a mask into a shaded 16x16 RGBA sprite."""
    grid = parse(mask)
    ramps = {
        "X": ramp(primary),
        "A": ramp(accent or primary),
        "B": ramp(third or accent or primary),
    }
    img = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    px = img.load()

    def solid(x, y):
        return 0 <= x < S and 0 <= y < S and grid[y][x] != "."

    # bounding box drives the highlight->shadow ramp so small icons shade
    # as convincingly as large ones
    ys = [y for y in range(S) for x in range(S) if grid[y][x] != "."]
    xs = [x for y in range(S) for x in range(S) if grid[y][x] != "."]
    if not ys:
        return img
    y0, y1, x0, x1 = min(ys), max(ys), min(xs), max(xs)
    h = max(1, y1 - y0)
    w = max(1, x1 - x0)

    for y in range(S):
        for x in range(S):
            ch = grid[y][x]
            if ch == ".":
                continue
            if ch == "o":
                px[x, y] = (glow[0], glow[1], glow[2], 255)
                continue
            outline, shadow, base, highlight = ramps.get(ch, ramps["X"])
            # a pixel on the silhouette edge is always the dark border
            if not (solid(x - 1, y) and solid(x + 1, y) and solid(x, y - 1) and solid(x, y + 1)):
                px[x, y] = outline
                continue
            t = ((y - y0) / h) * 0.65 + ((x - x0) / w) * 0.35
            px[x, y] = highlight if t < 0.28 else base if t < 0.68 else shadow
    return img


# ---------------------------------------------------------------------------
# The sprites. Authored so each silhouette is recognisable at inventory size.
# ---------------------------------------------------------------------------
MASKS = {
    "soul_shard": """
.......XX.......
......XXXX......
.....XXXXXX.....
.....XXooXX.....
....XXXooXXX....
....XXXooXXX....
.....XXooXX.....
.....XXXXXX.....
......XXXX......
......XXXX......
.......XX.......
.......XX.......
................
................
................
................
""",
    "spectral_dust": """
................
................
................
.....X..X.......
....X.XX.X..X...
...XX.X.XX.X.X..
..X.XXX.X.XX.X..
.XX.X.XXX.X.XX..
..XXX.X.XX.XX...
...X.XXX.XX.X...
....XX.X.X.X....
.....X..X.......
................
................
................
................
""",
    "ember_dust": """
................
................
................
.....X..X.......
....X.XX.X..X...
...XX.X.XX.X.X..
..X.XXX.X.XX.X..
.XX.X.XXX.X.XX..
..XXX.X.XX.XX...
...X.XXX.XX.X...
....XX.X.X.X....
.....X..X.......
................
................
................
................
""",
    "demon_horn": """
............XX..
...........XXX..
..........XXX...
.........XXX....
........XXXX....
.......XXXX.....
......XXXX......
.....XXXX.......
....XXXX........
...XXXX.........
...XXX..........
..XXXX..........
..XXXX..........
..XXX...........
...XX...........
................
""",
    "banshee_vocal_cord": """
.......XX.......
......XX.XX.....
.....XX...XX....
....XX.....XX...
....XX......XX..
...XX.......XX..
...XX.......XX..
...XX......XX...
....XX....XX....
....XX...XX.....
.....XX.XX......
.....XXXX.......
......XX........
......XX........
.....XXXX.......
................
""",
    "ember_core": """
................
......XXXX......
....XXXXXXXX....
...XXXooooXXX...
...XXoooooXXX...
..XXXoooooXXXX..
..XXXoooooXXXX..
..XXXoooooXXXX..
...XXoooooXXX...
...XXXooooXXX...
....XXXXXXXX....
......XXXX......
................
................
................
................
""",
    "sentinel_core": """
................
.......XX.......
.....XXXXXX.....
....XXXooXXX....
...XXXooooXXX...
..XXXoooooXXXX..
..XXoooooooXXX..
..XXXoooooXXXX..
...XXXooooXXX...
....XXXooXXX....
.....XXXXXX.....
.......XX.......
................
................
................
................
""",
    "ghost_ward_charm": """
.....BBBB.......
....B....B......
....B....B......
.....B..B.......
....XXXXXX......
...XXXooXXX.....
...XXoooXXX.....
...XXoooXXX.....
....XXooXX......
.....XXXX.......
......XX........
................
................
................
................
................
""",
    "featherfall_charm": """
.....BBBB.......
....B....B......
....B....B......
.....B..B.......
......XX........
.....XXXX.......
....XXXXXX......
...XXXooXXX.....
...XXoooXXX.....
....XXooXX......
.....XXXX.......
......XX........
................
................
................
................
""",
    "spirit_lantern": """
......BB........
.....B..B.......
....BBBBBB......
....BXXXXB......
....BXooXB......
....BoooXB......
....BooooB......
....BXooXB......
....BXXXXB......
....BBBBBB......
.....BBBB.......
................
................
................
................
................
""",
    "soul_compass": """
................
....BBBBBB......
...BXXXXXXB.....
..BXXXAXXXXB....
..BXXAAAXXXB....
..BXXXAXXXXB....
..BXXXXXXXXB....
..BXXXXAXXXB....
..BXXXAAAXXB....
...BXXXAXXB.....
....BBBBBB......
................
................
................
................
................
""",
    "journal": """
................
..BBBBBBBBBB....
..BXXXXXXXXB....
..BXoooooXXB....
..BXXXXXXXXB....
..BXooooXXXB....
..BXXXXXXXXB....
..BXoooooXXB....
..BXXXXXXXXB....
..BXXooXXXXB....
..BBBBBBBBBB....
................
................
................
................
................
""",
    "soulfire_igniter": """
..........AAA...
.........AAAAA..
........AAoAA...
.......AAAAA....
......BBB.A.....
.....BBB........
....BBB.........
...BBB..........
..BBB...........
..BB............
.BB.............
.B..............
................
................
................
................
""",
    "sigil_hollow_king": """
..XXXXXXXXXX....
..XXXXXXXXXX....
..XXAAAAAAXX....
..XXAXXXXAXX....
..XXAXoooAXX....
..XXAXoAoAXX....
..XXAXoooAXX....
..XXAXXXXAXX....
..XXAAAAAAXX....
..XXXXXXXXXX....
..XXXXXXXXXX....
................
................
................
................
................
""",
    "ember_coal": """
................
.....XXXX.......
....XXXXXX......
...XXXooXXX.....
...XXoooXXX.....
..XXXoooXXXX....
..XXXXoXXXXX....
..XXXXXXXXXX....
...XXXXXXXX.....
....XXXXXX......
.....XXXX.......
................
................
................
................
................
""",
    "veilsteel_plating": """
................
..XXXXXXXXXX....
..XAXXXXXXAX....
..XXXXXXXXXX....
..XXXXXXXXXX....
..XXXXXXXXXX....
..XXXXXXXXXX....
..XAXXXXXXAX....
..XXXXXXXXXX....
................
................
................
................
................
................
................
""",
    "chitin": """
.......XX.......
......XXXX......
.....XXXXXX.....
....XXXXXXXX....
....XXXXXXXX....
....XXXXXXXX....
.....XXXXXX.....
.....XXXXXX.....
......XXXX......
......XXXX......
.......XX.......
................
................
................
................
................
""",
    "embered_scale": """
.......XX.......
......XXXX......
.....XXXXXX.....
....XXXooXXX....
....XXoooXXX....
....XXXooXXX....
.....XXXXXX.....
.....XXXXXX.....
......XXXX......
......XXXX......
.......XX.......
................
................
................
................
................
""",
    "elk_hide": """
................
..XXX....XXX....
.XXXXX..XXXXX...
.XXXXXXXXXXXX...
..XXXXXXXXXX....
..XXXXXXXXXX....
...XXXXXXXX.....
...XXXXXXXX.....
....XXXXXX......
...XXXXXXXX.....
..XXX....XXX....
.XXX......XXX...
................
................
................
................
""",
    "elk_marrow": """
................
....XX....XX....
...XXXX..XXXX...
...XXXXXXXXX....
....XXXXXXX.....
.....XXXXX......
.....XXXXX......
.....XXXXX......
....XXXXXXX.....
...XXXXXXXXX....
...XXXX..XXXX...
....XX....XX....
................
................
................
................
""",
    "bat_membrane": """
................
..XX........XX..
..XXXX....XXXX..
..XXXXXXXXXXXX..
..XXXXXXXXXXXX..
...XXXXXXXXXX...
...XXXXXXXXXX...
....XXXXXXXX....
....XXXXXXXX....
.....XXXXXX.....
......XXXX......
................
................
................
................
................
""",
    "toad_mucus": """
................
................
................
......XXX.......
.....XXXXX......
....XXXoXXX.....
....XXoooXX.....
....XXXoXXX.....
.....XXXXX......
......XXX.......
................
....XX....XX....
................
................
................
................
""",
    "glimmershroom_item": """
................
.....XXXX.......
...XXXXXXXX.....
..XXoXXXXoXX....
..XXXXXXXXXX....
..XXXXoXXXXX....
...XXXXXXXX.....
.....BBBB.......
.....BBBB.......
.....BBBB.......
.....BBBB.......
....BBBBBB......
................
................
................
................
""",
    "ember_fruit": """
................
.........BB.....
........BB......
....AAAAA.......
...XXXXXXX......
..XXXoXXXXX.....
..XXooXXXXX.....
..XXoXXXXXX.....
..XXXXXXXXX.....
...XXXXXXX......
....XXXXX.......
................
................
................
................
................
""",
    "veil_marrow_stew": """
................
................
................
...AAAAAAAA.....
..AAoAAAAAAA....
..BBBBBBBBBB....
..BXXXXXXXXB....
..BXXXXXXXXB....
...BXXXXXXB.....
....BBBBBB......
................
................
................
................
................
................
""",
    "dragon_egg": """
................
......XX........
.....XXXX.......
....XXoXXX......
....XoXXXX......
...XXXXXXXX.....
...XXXXoXXX.....
...XXXXXXXX.....
...XXoXXXXX.....
...XXXXXXXX.....
....XXXXXX......
.....XXXX.......
................
................
................
................
""",
    # boss weapons - long diagonal blades, vanilla sword posture
    "hollow_kings_reaper": """
.............XX.
............XXX.
...........XXX..
..........XXX...
.........XXX....
........XXX.....
.......XXX......
..A...XXX.......
..AA.XXX........
...AAXX.........
..AAAAA.........
.BB.AA..........
BBB..A..........
BB..............
................
................
""",
    "wailing_edge": """
.............XX.
............XXX.
...........XXX..
..........XXX...
.........XXX....
........XXX.....
.......XXX......
..A...XXX.......
..AA.XXX........
...AAXX.........
..AAAAA.........
.BB.AA..........
BBB..A..........
BB..............
................
................
""",
    "malacodas_fang": """
.............XX.
............XXX.
...........XXX..
..........XXX...
.........XXX....
........XXX.....
.......XXX......
..A...XXX.......
..AA.XXX........
...AAXX.........
..AAAAA.........
.BB.AA..........
BBB..A..........
BB..............
................
................
""",
}
MASKS["sigil_weeping_widow"] = MASKS["sigil_hollow_king"]
MASKS["sigil_malacoda"] = MASKS["sigil_hollow_king"]

# primary / accent / third(handle) colours per icon
COLORS = {
    "soul_shard": ((120, 214, 200), (200, 255, 245), None),
    "spectral_dust": ((198, 176, 232), None, None),
    "ember_dust": ((226, 116, 40), None, None),
    "demon_horn": ((92, 44, 40), (60, 26, 24), None),
    "banshee_vocal_cord": ((214, 186, 226), (250, 235, 255), None),
    "ember_core": ((214, 84, 30), (255, 170, 60), None),
    "sentinel_core": ((216, 158, 54), (255, 226, 130), None),
    "ghost_ward_charm": ((120, 210, 190), (200, 255, 240), (150, 138, 108)),
    "featherfall_charm": ((186, 176, 224), (232, 226, 255), (150, 138, 108)),
    "spirit_lantern": ((196, 176, 96), (255, 246, 190), (92, 78, 52)),
    "soul_compass": ((196, 192, 178), (176, 64, 58), (150, 122, 70)),
    "journal": ((92, 44, 104), (232, 220, 186), (60, 28, 68)),
    "soulfire_igniter": ((132, 136, 146), (60, 70, 132), (128, 96, 56)),
    "sigil_hollow_king": ((214, 200, 164), (128, 92, 190), None),
    "sigil_weeping_widow": ((214, 200, 164), (186, 124, 204), None),
    "sigil_malacoda": ((214, 200, 164), (206, 82, 38), None),
    "ember_coal": ((62, 48, 44), (30, 24, 22), None),
    "veilsteel_plating": ((136, 146, 190), (92, 168, 236), None),
    "chitin": ((132, 110, 74), (90, 74, 48), None),
    "embered_scale": ((198, 96, 44), (255, 168, 70), None),
    "elk_hide": ((148, 118, 88), (110, 86, 62), None),
    "elk_marrow": ((226, 218, 202), (250, 246, 238), None),
    "bat_membrane": ((104, 84, 122), (70, 56, 84), None),
    "toad_mucus": ((132, 200, 108), (206, 250, 176), None),
    "glimmershroom_item": ((110, 196, 178), (206, 250, 236), (216, 220, 206)),
    "ember_fruit": ((202, 72, 44), (86, 132, 62), (110, 74, 40)),
    "veil_marrow_stew": ((176, 158, 128), (196, 172, 132), (128, 116, 104)),
    "dragon_egg": ((106, 58, 146), (196, 140, 240), None),
    "hollow_kings_reaper": ((222, 224, 240), (150, 108, 196), (104, 72, 44)),
    "wailing_edge": ((214, 196, 232), (132, 96, 158), (86, 62, 104)),
    "malacodas_fang": ((228, 108, 62), (150, 44, 26), (74, 38, 26)),
}

GLOWS = {
    "soul_shard": (214, 255, 244),
    "ember_core": (255, 214, 110),
    "sentinel_core": (255, 236, 160),
    "ghost_ward_charm": (206, 255, 240),
    "featherfall_charm": (236, 232, 255),
    "spirit_lantern": (255, 248, 200),
    "journal": (240, 226, 150),
    "soulfire_igniter": (120, 180, 255),
    "ember_coal": (255, 150, 60),
    "embered_scale": (255, 196, 96),
    "toad_mucus": (226, 255, 200),
    "glimmershroom_item": (222, 255, 246),
    "ember_fruit": (255, 186, 120),
    "veil_marrow_stew": (226, 206, 160),
    "dragon_egg": (226, 170, 255),
    "sigil_hollow_king": (198, 160, 255),
    "sigil_weeping_widow": (232, 178, 246),
    "sigil_malacoda": (255, 150, 90),
}


def render(name):
    mask = MASKS[name]
    primary, accent, third = COLORS[name]
    return shade(mask, primary, accent, third, glow=GLOWS.get(name, (255, 240, 180)))


def all_names():
    return sorted(MASKS)
